### ISSUE TITLE
[proposal] Rename {{cookiecutter.project_slug}} folder to 'apps'

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1086]
As of now, the generated project's [{{cookiecutter.project_slug}}](https://github.com/pydanny/cookiecutter-django/tree/f3ea2570ab6cfc981dca1b6a8f49852c91cbe2d7/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D) folder is named after the project itself, which is OK except that it might be misleading for cookiecutter-django newcomers to grasp its purpose at first.

IMO, **apps** name would suffice provided it's agreed upon for the folder to contain custom project _apps_, _static_, and _media_ files only.

What do you think?

**Comment by IvanAnishchuk** [comment]
I don't think `apps` is universal, some prefer `src` or something like that. (I'm also not quite sure about having `config` in a separate location, when all the python code is in the same directory it simplifies some tasks.)

And I think there is some possible value in having `project_slug`. If you, for example, want to distribute project code as eggs or otherwise install it somewhere, clear namespacing helps a lot.

**Comment by webyneter** [comment]
@luzfcb, thanks for valuable insights.
