### ISSUE TITLE
Introduce development-time Celery services

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1225]
For some reason, we don't have `celerybeat`, `celeryworker` (and `redis`) in `local.yml` development configuration while one can opt out to use them in production (and in production only, as of now) -- as far as I see, this presents a reproducibility issue for no good reason (or am I missing something, @pydanny, @jayfk, @luzfcb ?).

**Comment by chopanpma** [comment]
Shupeyko I was wondering the same. My conclusion was that in development you might not want automatic task running, you can run them from the command line, however Redis is still needed in dev.yml to do that.  Also celery version is outdated, do you know if it is for some specific reason not to upgrade?

**Comment by webyneter** [comment]
@chopanpma, I'm aware of no reason for `redis` not be upgraded, however, once done that would require careful testing, especially for production setup. You can provide a PR if you have time pinning `redis` to the latest minor version, and tested both for local and production environments.

**Comment by chopanpma** [comment]
Sorry I was talking about celery version, sure I would like to test
upgrading celery and send a PR.

On Jul 10, 2017 3:40 PM, "Shupeyko Nikita" <notifications@github.com> wrote:

@chopanpma <https://github.com/chopanpma>, I'm aware of no reason for redis
not be upgraded, however, once done that would require careful testing,
especially for production setup. You can provide a PR if you have time
pinning redis to the latest minor version, and tested both for local and
production environments.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pydanny/cookiecutter-django/issues/1225#issuecomment-314230020>,
or mute the thread

**Comment by smartfin** [comment]
Same question, it is a bit strange, that there is no celery by default.

**Comment by webyneter** [comment]
@chopanpma do you mean you want to upgrade Celery from 3.x to 4.x? If yes, there's already #945,  check it out.

I'm about to provide a PR replicating the production Celery/Redis configuration a bit later.

**Comment by chopanpma** [comment]
Yes I'll check, thanks
