### ISSUE TITLE
{% if cookiecutter.use_celery == 'y' %} compose section produces duplicate images

### ISSUE THREAD

**Issue by japrogramer** [pydanny/cookiecutter-django#1255]
Since these section shares the same dockerfile as the django project container, why dont we just have it use the built image for the django container and only override the command section?
Since that seems to be the major change. 
what is the rationale for having separate images?

**Comment by webyneter** [comment]
@japrogramer if you take a look at the docker images built for the generated project you'll see that every other service utilizing the `django` service's image has its image digest exactly the same as the `django` 's. The reason is that images based off of the same base one share common layers, and `celery*` services are no exception, they are indeed all the same images (identified with one and the same SHA256). Therefore, when building other `django` image-based services the usage of already existing union filesystem layers is logged and no real build operations are performed producing a number of formally distinct yet identical images (the original one existing physically, and others effectively referencing its layers in a "virtual" manner.)

I do agree that we could define `django`-based services by means of  `extend`ing the former to get more DRY. (Again, it wouldn't produce an identical copy of the base image but rather reference the existing one's layers to its entirety.)
