### ISSUE TITLE
Add other database support like MySQL and No-SQL database like MongoDB?

### ISSUE THREAD

**Issue by jarrekk** [pydanny/cookiecutter-django#1261]
Many develop use sqlite at local server and MySQL at production environment and MongoDB is also popular if we can use these configurations when we setup, it will be better.

**Comment by webyneter** [comment]
@jarrekk any extra database provider integration would require maintenance efforts from the community, especially when we talk about the project's Core team. 

Nevertheless, I think we can work something out should we move one step at a time. Let's give it a try with basic support for MySQL 5.7.x first since Django docs provide [a detailed guide on setting this one up](https://docs.djangoproject.com/en/1.10/ref/databases/#mysql-notes).

If you're still onto this I suggest that you deliver a PR addressing the above-mentioned requirements.
