### ISSUE TITLE
Integrate dependencies.io to upgrade Dockerfile base images

### ISSUE THREAD

**Issue by webyneter** [pydanny/cookiecutter-django#1336]
* [Sample configuration targeting Docker](https://www.dependencies.io/examples/).
    * [Docs](https://www.dependencies.io/docs/collectors/dockerfile/).
* [Free for Open Source](https://www.dependencies.io/pricing/).

**Comment by davegaeddert** [comment]
I work on dependencies.io and would be happy to help with this if you have any questions. I haven't used this particular cookiecutter in a long time but we do use cookiecutter in our dependencies.io command line tool!

**Comment by jayfk** [comment]
I see a couple of problems:

- We currently support multiple releases for the Python and the Postgres image (this will be hard to upgrade).
- Pinning on the latest bugfix release might not be a good idea for the users of Cookiecutter Django:
  - `docker pull python:3.6` will  update the docker image to the latest `3.6` release, whereas `docker pull python:3.6.1` will update to the latest `3.6.1` release. What if `3.6.2` comes out and has an important security fix?
  - Staying on the latest major release is safer in this regard as it allows people to use dockers tools to update their images.

**Comment by davegaeddert** [comment]
> multiple releases for the Python and the Postgres image

Is this done with cookiecutter and a template for the Dockerfile?

> Pinning on the latest bugfix release might not be a good idea

I see what you mean here. From an end-user's perspective, I actually do like to use `python:3.6.1` so that I know and can trace back to the commit where it got updated to `python:3.6.2` (in case something did happen to go wrong). Part of the reason I like to do it that way now though is because I get that update PR automatically with dependencies.io...but I'm not sure if that's a call you want to make from a cookiecutter perspective.

I guess the only other question that comes to mind would be whether it is valuable enough to receive updates for the minor releases, which are pretty few and far between... 3.6 -> 3.7, etc.

> The collector fails on jinja templates

I'm not opposed to adding jinja support to the [collector](https://github.com/dependencies-io/collector-python-pip), if we can find a good way to do it. We don't want to support *every* possible way of doing things (outside of letting people build custom collectors/actors), but to me jinja is common enough in the python world that it seems like something we could support out-of-the-box. I personally used to have a similar issue when using saltstack. I opened an issue for that [here](https://github.com/dependencies-io/collector-python-pip/issues/15) and will probably try to look into it whether or not you end up using it. Given all the other things discussed above though, automatic updates for these python requirements files seems like the best thing dependencies.io could do for this project since you're already pinning those requirements and would want your users to at least be getting the latest patch update to those, I would think. I see some pyup stuff in there, is pyup able to update those templates or is that just for end-users?

Thanks for taking the time @jayfk.

**Comment by webyneter** [comment]
> We currently support multiple releases for the Python and the Postgres image (this will be hard to upgrade).

I don't recall us having multiple Python releases on support track: we've always been sticking with the latest one provided proper migration efforts had been taken; furthermore, we are explicitly not backward-compatible. Regarding postgres, -- yes, not sure if dependencies.io will be capable of editing `cookiecutter.json`.

> Pinning on the latest bugfix release might not be a good idea for the users of Cookiecutter Django: 

I wasn't saying we should, on the contrary, we've got all Docker service image versions pinned to minors of am I missing something here?

> The collector fails on jinja templates: jayfk/dependencies.io-test#2 (comment)

If this hasn't been fixed yet, then I consider it to be the only blocker (taking into account my assumption about `cookiecutter.json` from the first point which I think we can live with).

@jayfk thoughts?

**Comment by webyneter** [comment]
I see jinja still fails.

**Comment by jayfk** [comment]
I think we are fine with how we are handling this right now.

**Comment by webyneter** [comment]
Yeah, I'm closing this one for now unless we can be sure of seamless integration out of box.
