### ISSUE TITLE
Use with Celery 4.x

### ISSUE THREAD

**Issue by narnikgamarnikus** [pydanny/cookiecutter-django#1353]
I use cookiecutter-django with celery==3.1.25. 
Now I need use tasks scheduler, and my opinion, best way for this - it's celery beat. 

But [here](https://github.com/celery/django-celery-beat/issues/3#issuecomment-249666479) I found information that celery-beat works with Celery version 4.x

[Here](https://github.com/pydanny/cookiecutter-django/pull/1249) I saw the information that pyup-bot on July 24 offered to update Celery to version 4.1.0, but this issue is still open.

Prompt, how to be in my situation? I like cookiecutter-django and I'm using it now in my project, but also, I really need a task scheduler.

I have not yet tried to replace the version of Celery, but I think that this will lead to a number of mistakes, otherwise it would have been done before me.

**Comment by sfdye** [comment]
Celery 3.1 comes with beat already:
http://docs.celeryproject.org/en/3.1/userguide/periodic-tasks.html

You just need to define `CELERYBEAT_SCHEDULE` in your `base.py`
```
CELERYBEAT_SCHEDULE = {
    'add-every-30-seconds': {
        'task': 'tasks.add',
        'schedule': timedelta(seconds=30),
        'args': (16, 16)
    },
}
```

**Comment by narnikgamarnikus** [comment]
@sfdye I need to create tasks with a certain time interval in the signals.

**Comment by sfdye** [comment]
@narnikgamarnikus 

I did not get your problem. Is that something celery beat can't do for you?

**Comment by narnikgamarnikus** [comment]
@sfdye , until then, I used PeriodicTask and IntervalSchedule, which provided celery beat. 
The way that you describe, is suitable for several repetitive tasks. In my case, the tasks need to be added and deleted dynamically. I need to pass various arguments to the task, whereas in your example, the arguments are static.

**Comment by sfdye** [comment]
@narnikgamarnikus 
For dynamic arguments, you can use the `kwargs` fields: 
http://docs.celeryproject.org/en/3.1/userguide/periodic-tasks.html#available-fields

To add or delete task, you can do so from django admin:
http://docs.celeryproject.org/en/3.1/userguide/periodic-tasks.html#using-custom-scheduler-classes

And now this is not a cookiecutter-django issue, it's a celery issue. If you want to use features in celery 4.X, #1249 needs to be closed first, which I don't think will happen soon.

**Comment by DanielStevenLewis** [comment]
@narnikgamarnikus try to install django-celery instead of django-celery-beat. django-celery works with Celery 3 (unlike django-celery-beat). You can then, for example import PeriodicTask from djcelery.models instead of from django_celery_beat.models . This allows you to add/delete/manipulate tasks both dynamically AND PROGRAMMATICALLY (not only from the Django admin site). The drawback to this workaround is that if one doesn't need django-celery for anything other than this, then it bloats one's app. Thus, It would be better to have Celery 4.0 included in cookiecutter-django so that django-celery-beat models can be used. @jayfk and @sfdye Shouldn't this issue be re-opened, or is there an alternative way to import PeriodicTask, or is there an alternative approach I'm unaware of?
