### ISSUE TITLE
Error documents about DJANGO_ADMIN_URL

### ISSUE THREAD

**Issue by bviews** [pydanny/cookiecutter-django#1365]
**Note: for support questions, please use the `cookiecutter-django` tag on stackoverflow**. This repository's issues are reserved for feature requests and bug reports. If you need quick professional paid support for your project, contact support@cookiecutter.io.

* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug report

* **What is the current behavior?**
https://cookiecutter-django.readthedocs.io/en/latest/settings.html
It says DJANGO_ADMIN_URL **Development Default**  is  r’^admin/’, 

but if I set my .env as below in my production environment, It wouldn't work.
```
DJANGO_ADMIN_URL=r’^admin/’
```

If I change it to ^admin/ It work,
So I think it should be 
```
DJANGO_ADMIN_URL=^admin/
```

**Comment by sfdye** [comment]
The doc is not wrong, let me make it clear.

> It says DJANGO_ADMIN_URL Development Default is r’^admin/’,

This is because in the [base setting][base.py], you have:
```
ADMIN_URL = r'^admin/'
```

First of all, `DJANGO_ADMIN_URL` is an environment variable to be used with `django-environ`, it is NOT a Django setting.

Second, `.env` is only required for `production` env, for `local` env you don't need to override this value. For production, you will alway want to set the admin url to some secret value for security reasons. You can also check out the `django-admin-honeypot` package.

Third, you are right. If you need to override the `DJANGO_ADMIN_URL` value in the `.env` file, this is the correct format:

```
DJANGO_ADMIN_URL=^some-secret-value/
```

[base.py]: https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/base.py#L288

**Comment by bviews** [comment]
Seems like I misunderstand about the documents of settings.
thx for the reply.

**Comment by sfdye** [comment]
No problem. Feel free close the issue :)
