### ISSUE TITLE
Update to Django 2.x

### ISSUE THREAD

**Issue by brylie** [pydanny/cookiecutter-django#1416]
Now that [Django 2.0 has been released](https://www.djangoproject.com/weblog/2017/dec/02/django-20-released/), it would be nice for Cookiecutter Django to work towards 2.0 support. What is involved in supporting Django 2.0? What dependencies should be upgraded and/or deprecated to move towards Django 2.0 support?

**Comment by luzfcb** [comment]
I finally got 15 days off from my work, starting next week. So I plan, at some point, to pay attention to #1111 and this one.

**Comment by pydanny** [comment]
@luzfcb Feel free to push this through however is easiest for you. If you want to bump Cookiecutter Django to 2.0 and have people open tickets if they break, that works for me.

**Comment by epicwhale** [comment]
+1

**Comment by markliederbach** [comment]
I don't suppose there is a way to select which django version going forward? With 1.11.x supported through 2020, and many enterprise folks still stuck in Python 2.x, it'd be nice to easily switch between the two versions.

**Comment by pydanny** [comment]
Sorry, @markliederbach, but without significant team financing we can't support python 2.7 going forward. And none of us have the free time to do the legwork to get that money.

However, if you want to organize the ongoing gathering of funds to pay for maintenance of this project to support 2.7 going forward, then we can consider it.

**Comment by pydanny** [comment]
For reference, the current budget of Cookiecutter Django is $0/month. We've never been able to secure any funding.

**Comment by pydanny** [comment]
For a while I paid for my time on this project thanks to Two Scoops of Django. But sales of TSD haven't been that good this time around (few reviews on Amazon for 1.12 and lack of support from the DSF). Also since the start of 2016 my bills increased substantially because a family member has significant medical bills. Hence why maintenance has lasted on my part.

**Comment by epicwhale** [comment]
@pydanny, team - I've added a pull request for this #1421 - let me know if that helps?

I noticed only a few changes are needed to upgrade to 2.0 based on the release notes here: https://docs.djangoproject.com/en/2.0/releases/2.0/

**Comment by KrunchMuffin** [comment]
Any word on the PR?

**Comment by foarsitter** [comment]
PR #1421 fails on the last_name @epicwhale since [last_name max_length is creased to 150](https://docs.djangoproject.com/en/2.0/releases/2.0/#abstractuser-last-name-max-length-increased-to-150). Can we edit the [existing migration](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/users/migrations/0001_initial.py#L25) or do we have to create an other one?

**Comment by epicwhale** [comment]
@foarsitter I just let django `make` the migrations for me and it generated an alterfield migration on the last_name field in the User model.

```
# Generated by Django 2.0 on 2017-12-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
```
