### ISSUE TITLE
Remove elastic beanstalk support

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#1417]
While we use Elastic Beanstalk (and a lot of Lambda deployments), the truth is I don't have time to support it here on this project. As it adds extra complexity and without any support, removing it will make the maintenance burden on this project lighter.

**Comment by sfdye** [comment]
I agree, EB requires a lot of customization and the deployment is very slow. Our team is already moving away from it to ECS.

**Comment by dongbosong** [comment]
I have been struggling with beanstalk deployment for a few days and could not get it to work. Basically, after setting everything up and with the app showing healthy status, I get 'connecting ...' blank page when trying to connect to the server. I have tried to check log messages and other stuff but could not find what was wrong.

Since a fresh standard Django project works on EB, I am facing the dilemma as whether I should start from a standard project and add all the goodies from this template manually, or remove suspicious pieces from this template until I find the culprit.  It would not be pleasant in either case.

**Comment by pydanny** [comment]
Removed in 793a46ba45229cf26c67d760c4b1df767a9e0f12.
