### ISSUE TITLE
ProgrammingError: relation "auth_user" does not exist 

### ISSUE THREAD

**Issue by raushanraj** [pydanny/cookiecutter-django#146]
When i try to add user using admin this give error

ProgrammingError: relation "auth_user" does not exist
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...

**Comment by KushGoyal** [comment]
thanks!

**Comment by eeriksp** [comment]
I had the same issue with a Django project.
I created the superuser through `manage.py createsuperuser` which worked out fine, but when I tried to log in via the web interface, I got the described error.
The reason was that I was using production settings when I ran the server, but development settings when using `manage.py`. So the superuser was created to the development Sqlite database, while the server tried to access the production Postgres database where no migrations had been performed yet.

In case anybody runs into the same issue:

1. use `manage.py the_command --settings the.real.settings`
2. or set the `DJANGO_SETTINGS_MODULE` to hold the right settings.

**Comment by mavhungutrezzy** [comment]
I encountered the same errors as described in this post, but in my case, the issue was that I was using ```from django.contrib.auth.models import User``` instead of ```from django.contrib.auth import get_user_model```. After some investigation, I realized that the cause of the error was related to my **custom User model**, which I had created by subclassing ```AbstractUser```. Once I made the change to use ```get_user_model()```, the errors were resolved.
