### ISSUE TITLE
How to properly generate startapp in cookiecutter

### ISSUE THREAD

**Issue by randolphpebenito** [pydanny/cookiecutter-django#1505]
I've just successfully cloned this repo and everything works fine. My only question is how to generate the properly the startapp.

Normal way:
./manage.py startapp <APP NAME>  

Is it the same way when you use cookiecutter as the boilerplate?

**Comment by browniebroke** [comment]
Hi, cookiecutter is a project template to help you generate a production-ready project template. Once you have your project, it's a regular Django project and all the regular [Django admin commands](https://docs.djangoproject.com/en/2.0/ref/django-admin/) apply, as well as the ones from [django-extensions](https://django-extensions.readthedocs.io/en/latest/command_extensions.html) locally.

So, yes, the "normal way" still applies, this cookiecutter doesn't provide any hooks to add apps within your project.

If you're looking into creating a reusable, standalone Django app (rather than a Django project), you may want to use [cookiecutter-djangopackage](https://github.com/pydanny/cookiecutter-djangopackage) instead.
