### ISSUE TITLE
Environment variables will work with mod_wsgi

### ISSUE THREAD

**Issue by ncoghlan** [pydanny/cookiecutter-django#160]
Graham Dumpleton tells me that the claim environment variables will not work with mod_wsgi is incorrect.

**Comment by carljm** [comment]
Hi all!

I just marked the ticket @pydanny opened as `needsinfo` because it's not clear what action is being requested from Django. If anyone can help clarify that, the ticket is at https://code.djangoproject.com/ticket/24326 - feel free to reopen if you can provide some clarity.

I'm not entirely sure what @ncoghlan was referring to in terms of the default Django `wsgi.py` file being "incomplete", nor am I clear why @grahamdumpleton 's gist recommends creating a new WSGI application file next to it, rather than editing the default one. The main issue I'm aware of where Django's default `wsgi.py` file interacts poorly with `mod_wsgi` is described in https://code.djangoproject.com/ticket/18518 (and related https://code.djangoproject.com/ticket/18559). This issue is already discussed in detail in our "hosting with mod_wsgi" docs: https://docs.djangoproject.com/en/1.7/howto/deployment/wsgi/modwsgi/

**Comment by pydanny** [comment]
Closing as it's being handled in Django itself, which is a more appropriate location for the discussion.
