### ISSUE TITLE
Replace awesome-slugify

### ISSUE THREAD

**Issue by hongquan** [pydanny/cookiecutter-django#1618]
* **I'm submitting a ... **
  - [x] feature request

* **Do you want to request a *feature* or report a *bug*?**

I don't know if this one is feature or bug.

* **What is the current behavior?**

_cookiecutter-django_ is using [awesome-slugify](https://github.com/dimka665/awesome-slugify) as dependency for new Django project, which requires to have very old _Unidecode_ (<0.05) while current one is 1.0.22.

* **What is the expected behavior?**

Please drop use of _awesome-slugify_.

* **What is the motivation / use case for changing the behavior?**

Replace _awesome-slugify_ with something more up-to-date will help Django project generated by _cookiecutter-django_ up-to-date with new libraries.

**Comment by browniebroke** [comment]
Thanks for the report. Looking at the [release history](https://libraries.io/pypi/Unidecode) for Unidecode, a requirement of <0.05 is not _that old_, it will install a release from Jun 2017. Is it causing any specific problems on your end?

I can see [there is an issue open](https://github.com/dimka665/awesome-slugify/issues/35) in `awesome-slugify` for lifting this restriction... Rather than dropping this dependency in `cookiecutter-django`, maybe it would be better to fix it upstream, in `awesome-slugify`? Have you tried submitting a pull request to the project? 

Even if we drop this dependency, we would need to find a candidate for replacement. Do you have any to suggest?

**Comment by webyneter** [comment]
@hongquan any news on this one regarding @browniebroke's suggestion?

**Comment by hongquan** [comment]
@browniebroke, @webyneter 
The alternative can be [python-slugify](https://github.com/un33k/python-slugify).

**Comment by browniebroke** [comment]
Good find. It's true that awesome-slugify's development seems a bit stalled. 

The slugify API doesn't seem used directly in the project but is a good utility to have, as pointed out in #761. The main API for both libraries is the same:

```python
from slugify import slugify

slugify('Any text')  # 'Any-text'
```

Therefore, I don't have any objections to this replacement.

**Comment by webyneter** [comment]
@browniebroke me neither.

**Comment by TobitRE** [comment]
You've overlooked one crucial difference.
awesome-slugify support German umlaute like ä, ü, ö and transform them to ae, ue, oe.

python-slugify only change it to a, u, o which is not well readably for user.
