### ISSUE TITLE
Remove outdated reference to grunt

### ISSUE THREAD

**Issue by jcass77** [pydanny/cookiecutter-django#1721]
It looks like we might have missed a reference to grunt in the README as part of #1636: https://github.com/pydanny/cookiecutter-django/blame/95ee1f159ddaf481192e49235738785d1bfb8427/%7B%7Bcookiecutter.project_slug%7D%7D/README.rst#L91-L92

Not sure what the gulp equivalent should be though - is it as simple as running [Mailhog](https://github.com/mailhog/MailHog/blob/master/docs/DEPLOY.md) for all deployments?

**Comment by sfdye** [comment]
Good find. I don't understand either why we need grunt here.

@webyneter Isn't this enough to use mailhog for non-docker setup? 
https://cookiecutter-django.readthedocs.io/en/latest/developing-locally.html#mailhog

**Comment by browniebroke** [comment]
Thanks @jcass77. You can see what Grunt was doing [here](https://github.com/pydanny/cookiecutter-django/blob/803616879afe0d45e82053d6ccba2e9516fd944d/%7B%7Bcookiecutter.project_slug%7D%7D/Gruntfile.js#L121-L123).  It's pretty simple, but not applicable for Docker.

In non-Docker + Gulp setup, we can implement a Gulp equivalent, by defining a task like [this one](https://github.com/pydanny/cookiecutter-django/blob/4a090b86722eff4028fa848e4bb8db092fe3e2a5/%7B%7Bcookiecutter.project_slug%7D%7D/gulpfile.js#L108-L115), but starting Mailhog instead of Django, and add it [to the default task dependencies](https://github.com/pydanny/cookiecutter-django/blob/4a090b86722eff4028fa848e4bb8db092fe3e2a5/%7B%7Bcookiecutter.project_slug%7D%7D/gulpfile.js#L137). This way, Mailhog would start in the background.

**Comment by webyneter** [comment]
@sfdye yes, it should, I specifically revised the non-Docker Mailhog docs a few months ago.
