### ISSUE TITLE
New apps created are located in the project root, not inside the project slug

### ISSUE THREAD

**Issue by JCepedaVillamayor** [pydanny/cookiecutter-django#1725]
## What happened?
When creating a new app using `python manage.py startapp <name-of-the-app>`, the application is created within the project root

## What should've happened instead?
The application should be created within the project slug, as indicated [here](https://github.com/pydanny/cookiecutter-django/blob/6865f5b21fb8bf522bc12237ba17323999f803f0/%7B%7Bcookiecutter.project_slug%7D%7D/manage.py#L26)

## Steps to reproduce
- Create a bare new application using _cookiecutter-django_
- Install all requirements into your virtualenvironment using `pip install -r requirements/local.txt`
- Try to create a new app (with the name foo, for instance) using `python manage.py startapp foo`

**Comment by luzfcb** [comment]
@JCepedaVillamayor 

> What happened?
When creating a new app using python manage.py startapp <name-of-the-app>, the application is created within the project root

this is the **expected behavior**, because cookiecutter-django does not change the way that django startapp works. ( [I tried doing this in another branch](https://github.com/pydanny/cookiecutter-django/commit/b3271b940406604a28830abb077bd71425d2dd06), but, I did not like having to rewrite almost everything to include this relatively simple logic.  the django startapp, apparently, was not projected to be extended :cry: )

you'll have to fix this manually:

1 - create the `<name-of-the-app>` app with python manage.py startapp
2 - move `<name-of-the-app>` directory to `<project_slug>` directory
3 - edit `<project_slug>/<name-of-the-app>/apps.py` and 
change `name = "<name-of-the-app>"` to `name = "<project_slug>.<name-of-the-app>"`
4 - add `"<project_slug>.<name-of-the-app>.apps.<NameOfTheAppConfigClass>",` on your [`LOCAL_APPS` on `config/settings/base.py`](https://github.com/pydanny/cookiecutter-django/blob/6865f5b21fb8bf522bc12237ba17323999f803f0/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/base.py#L79)


if that is enough to answer the question. please close this issue.
We gladly accept code and documentation contributions.

**Comment by JCepedaVillamayor** [comment]
Oh, I see, I misunderstood the meaning of the comment. Thank you for the manual fix, this was the steps I were doing before.

I'll be glad to document the project if needed (maybe on Troubleshooting?)

I close the issue for now, let's see how we proceed then.

**Comment by reyesvicente** [comment]
Why am I getting a `ModuleNotFoundError: No module named '<project_slug>.<name-of-the-app>.urls'` when I add the new app onto the config/urls.py?

**Comment by cjauvin** [comment]
As a newcomer to both Django and `cookiecutter-django`, I was confused by two aspects related to this issue:

1. I created a "Polls" app (from the Django tutorial) to compare both structures, and realized they were different
2. It was not clear to me, after having run `cookiecutter-django`, whether I needed to also explicitly create an app afterward or not (it seems that it is the case, because only the "Users" app is created right after the project has been generated)

**Comment by changeling** [comment]
This would seem to be a subject/issue worthy of documentation, perhaps inclusion in the startapp work flow. I see manual fixes presented as a reply to an issue, but surely this is worth addressing to the wider audience who may not come into the issues for a solution? Is this just me?

**Comment by mohyddintash** [comment]
I'm not sure if it helps, but here is what I do:

- cd into the project_slug directory
-  run `python ../manage.py startapp <name_of_app>`

This way it is created inside the project_slug directory.

**Comment by polakDas** [comment]
I found a great way to solve this issue.
To execute it, navigate to the desired directory and run the command ```django-admin startapp <app_name>```.
This allows you to easily organize your apps in separate folders.

**Comment by felix0xff** [comment]
> I'm not sure if it helps, but here is what I do:
> 
>     * cd into the project_slug directory
> 
>     * run `python ../manage.py startapp <name_of_app>`
> 
> 
> This way it is created inside the project_slug directory.

Develop locally with docker, and started an app in this way, the program itself runs normally, but when running pytest and building docs service, there are an error: ModuleNotFoundError: No module named '<name_of_app>'

Do we need to change some confs in pytest and sphinx?

**Comment by WoosterInitiative** [comment]
> I found a great way to solve this issue. To execute it, navigate to the desired directory and run the command `django-admin startapp <app_name>`. This allows you to easily organize your apps in separate folders.

Please make sure to follow the rest of the steps in https://github.com/cookiecutter/cookiecutter-django/issues/1725#issuecomment-407493176 to make sure everything else works.

I'd love to see this clearly delineated in the docs and perhaps even a management command to at least automate these steps post-app-creation.

Thoughts?

**Comment by tkozuch** [comment]
> > I found a great way to solve this issue. To execute it, navigate to the desired directory and run the command `django-admin startapp <app_name>`. This allows you to easily organize your apps in separate folders.
> 
> Please make sure to follow the rest of the steps in [#1725 (comment)](https://github.com/cookiecutter/cookiecutter-django/issues/1725#issuecomment-407493176) to make sure everything else works.
> 
> I'd love to see this clearly delineated in the docs and perhaps even a management command to at least automate these steps post-app-creation.
> 
> Thoughts?

that would be super helpful especially, one never knows when the comment becomes out of date etc
