### ISSUE TITLE
Cannot generate docs in docker

### ISSUE THREAD

**Issue by sww314** [pydanny/cookiecutter-django#1727]
## What happened?
if you try to run the makefile in the docs directory, make is not installed.

$ docker-compose -f local.yml run --rm django make 
Starting test_postgres_1 ... done
PostgreSQL is available
/entrypoint: exec: line 43: make: not found

Obviously, I can add make to docker. What I was wondering is makes sense to generate another Docker image just building the docs that way do not add bloat to the main Django image. You could also use the docs image in CI/CD pipeline to build your documentation in a separate step.

**Comment by step21** [comment]
Is still valid?
I just run makemessages / compilemessages and that works

**Comment by browniebroke** [comment]
@step21 `makemessages` & `compilemessages` are for translations, which works fine. This issue is about generating docs for the django project, which is based on running [this Makefile](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/docs/Makefile), using [GNU Make](https://www.gnu.org/software/make/).

As @sww314 pointed out, it looks like the command `make` is not found, which is probably because it it's not pre-installed in the Alpine base image we are using.

@sww314 I think it's fine to install it in the local image.

**Comment by step21** [comment]
Yeah, I know makemessages and compilemessages are for translations and that they work. Somehow I though that the Makefile was also for translations.
I do not mind if it is added, though it would probably be not a lot of bloat... (for comparison I just added graphviz and pygraphviz to my local image and as pygraphviz seemed to need a lot of dev dependencies (or maybe I missed something) it blew the image up by a lot.

**Comment by browniebroke** [comment]
We're now providing a `docs` service in the local docker-compose stack. I think we can close this issue.
