### ISSUE TITLE
Add warning to upgrade contrib.sites.migrations.0001 when upgrading from Python 2.x to 3.x

### ISSUE THREAD

**Issue by florianm** [pydanny/cookiecutter-django#1738]
## Description

[//]: # (What's it you're proposing? How should it be implemented?)

I'd like to suggest to include a note/warning/docs section on a unicode/bystestring tripwire users will encounter when upgrading a cookiecutter-django project which was generated under Python 2.x / Django 1.x to Python 3.x / Django 2.x.

Use case:
* A Django project was generated using cookiecutter-django in a Python 2.7 / Django 1.9 environment (latest Django at the time).
* Django migrations generate the occasional explicit bytestrings, e.g. at model manager names (`b'objects'`).
* Django project gets upgraded to Python 3.x / Django>2.0 (drops Python 2.x support).
* Python 3 strings expect to be unicode, Django will trip over bytestrings - this breaks migrations with explicit `b'bytestrings'`.
* Debugging Django leads the user towards django.contrib.sites - easy to confuse django's core module with the one pasted by cookiecutter-django!
* Confusion, troubleshooting and resolution see https://code.djangoproject.com/ticket/29632

As an artefact of using cookiecutter-django under Python 2, and c-d's inclusion of a project-side contrib.auth.sites, the stray bytestring in the project-side contrib.auth.sites migration 0001 escaped my attention longer than it should have. Note this bytestring is generated when running cookiecutter-django under Python 2.x -- it's not in [c-d's template for this migration](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/contrib/sites/migrations/0001_initial.py#L40)!

Could some kind of reminder be included? c-d does a great job including rationale e.g. [https://cookiecutter-django.readthedocs.io/en/latest/faq.html#why-is-there-a-django-contrib-sites-directory-in-cookiecutter-django why is there a django-contrib-sites].

## Rationale

[//]: # (Why should this feature be implemented?)

It would help users upgrading their Python and Django environment when they get stuck at this spurious bug.

## Use case(s) / visualization(s)

[//]: # ("Better to see something once than to hear about it a thousand times.")

Possibly a separate top level entry in the docs "Upgrading a cookiecutter-django project from Python 2.x to 3.x / Django 1.x to 2.x" and a fat warning in the autogenerated settings linking to that section in the docs. Happy to send PR if appropriate!

**Comment by browniebroke** [comment]
Hi Florian. I don't think a top-level section in the docs is worthwhile, however, there could be a paragraph about keeping a generated project up-to-date in the FAQ, as I think it's a recurrent question. 

At the moment, cookiecutter-django (and any cookiecutter template in general AFAIK) does not support anything beyond the point of initial generation. The generated template is not tied to the template in any way. If you familiar with React and create-react-app, the behaviour [is similar to using eject](https://medium.com/@shubheksha/tweaking-configuration-for-react-scripts-in-create-react-app-d91e9d03a42f), and that's the only option. The section would be stating this explicitly, that this is not a supported feature.

This section could also point to some resources on how to manage upgrades including Python 2 to 3 upgrades. There are great resources out there:

- [Python.org](https://docs.python.org/3/howto/pyporting.html)  
- [PyCon 2017 keynote](https://www.youtube.com/watch?v=28jA0uP7W6w)

You encountered this specific gotcha in that migration, but more generally, having byte string instead of Unicode strings in migrations & code will cause issues. Depending on your setup, Celery may have issues dequeuing tasks using Python 3 which have been put in the queue using Python 2. Django caches need to be invalidated when migrating... 

My point is documenting all of this in c-d isn't appropriate, IMO, but linking to more resources, maybe.

**Comment by florianm** [comment]
Would you like me to PR a section in the FAQ then? E.g. something along the lines of:

## Upgrading a cookiecutter-django based project from Python 2.x to 3.x
* Context: Python 2.x, Django 1.x, c-d generated project. Django 1.x creates the odd explicit bytestring, e.g. in migrations.
* Situation: User upgrades Python 2.x to 3.x and encounters errors, such as my issue with the custom "sites" (mention error messages so that a Google search for those will lead the user here)
* Diagnostics: Mention diagnostics, e.g. `grep -rn "[!a-zA-Z0-9]b'" .` to find bytestrings inside project dir
* Further reading: link some good resources
* Still stuck? Raise an issue

**Comment by florianm** [comment]
My intention is to turn the hours I've lost on my own inability to find that little bytestring (my grep regex wasn't good enough) in a place I didn't look (c-d's custom "sites") into a section in docs/faq that a web search will bring up when the next users will get stuck with the same issue. 
It's of course absolutely not cookiecutter-django's responsibility to handle the Python upgrade (especially since it's a "react eject" style once-off project template), I'm only hoping to place a solution to that problem in a discoverable place.

**Comment by browniebroke** [comment]
I appreciate your efforts in trying to help others facing the same issues you had. And simply opening this issue with that amazing level of details might already do the job. If I had the same issue today, Googling would probably bring this issue or the Django one up thanks to you and would unblock someone me.

Anyway, yes, pull request welcome. Given the nature of the content, what do you think of adding it to the troubleshooting section actually? Would it make more sense than FAQ?

**Comment by florianm** [comment]
You're right, troubleshooting section makes most sense! I'll write up a draft and send a PR shortly.

**Comment by webyneter** [comment]
@florianm any updates on this one?

**Comment by florianm** [comment]
@webyneter apologies, pulled sideways by other projects. Will send PR in coming week.

**Comment by webyneter** [comment]
@florianm any updates? :)

**Comment by browniebroke** [comment]
I'm closing this old issue. It's been more than 3 years that we [dropped support for Python 2](https://github.com/pydanny/cookiecutter-django/pull/1130), and documentaing this migration is no longer in scope of the project. This issue in itself does a good enough job for it.

One thing that helped me in the past which isn't mentioned in this thread yet is the [excellent `pyupgrade` library](https://pypi.org/project/pyupgrade/).

**Comment by florianm** [comment]
Sorry, I never got around to send a PR, and thanks for all the feedback. Hope this issue is enough to get others unstuck!
