### ISSUE TITLE
Error while Migration.

### ISSUE THREAD

**Issue by Chhaya02** [pydanny/cookiecutter-django#1778]
![model](https://user-images.githubusercontent.com/20675052/44907477-a7823380-ad35-11e8-8354-57ee256788e6.png)
![terminal error](https://user-images.githubusercontent.com/20675052/44907485-afda6e80-ad35-11e8-9784-580da12fe165.png)

I am trying to run migration but getting this error : 
ValueError: Related model 'users.User' cannot be resolved.

**Comment by webyneter** [comment]
@Chhaya02 try setting `AUTH_USER_MODEL` django setting to `<your users app import path>.User` and using `get_user_model()` std lib function to get current user model.

**Comment by Chhaya02** [comment]
@webyneter In my setiings file AUTH_USER_MODEL is defined and and I am trying to create the Custom user model, and no other table is included in this migration. Only trying to create custom User model and getting this error. get_user_model() std lib function will be used when I need the current user.

**Comment by luzfcb** [comment]
without seeing complete code, it is complex to find out what the real cause of the error is.

That said, your migration `0002_auto_20180831_1012.py` seems to re-create the User model

which in theory should not occur, [because according to](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/users/migrations/0001_initial.py#L14) the user table is created on 0001 migration.

**Comment by browniebroke** [comment]
Fábio is right, the migrations aren't the ones from `cookiecutter-django`... 

I think it's because you re-created the migrations for the users app, but with the first one is empty (you ran `python3 manage.py makemigrations --empty users`). However, this isn't supported by Django [according to the official docs](https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#changing-to-a-custom-user-model-mid-project):

> Due to limitations of Django’s dynamic dependency feature for swappable models, the model referenced by AUTH_USER_MODEL must be created in the first migration of its app (usually called 0001_initial); otherwise, you’ll have dependency issues.

I'm closing this, it's not a problem with this project.
