### ISSUE TITLE
Collectfast and Django 1.7+

### ISSUE THREAD

**Issue by antonagestam** [pydanny/cookiecutter-django#187]
The way Collectfast is added to `INSTALLED_APPS` ([here](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D/config/production.py#L77)) may be problematic for Django 1.7+, see this thread for more information: https://github.com/antonagestam/collectfast/issues/49#issuecomment-73836059

I'd suggest moving it to common.py and adding `COLLECTFAST_ENABLED = False` to local.py if Collectfast really isn't wanted there. However I don't really see why you'd want it installed on production only but there might be reasons to that that I don't know of.

**Comment by theskumar** [comment]
`Collectfast` was added to production only because S3 config were introduced only in `production.py`. We didn't wanted to have `Collectfast` as common requirement. 

I don't think there is any harm moving it to `common.py` with proper commented doc, given your explanation above. 

@pydanny thoughts?

**Comment by theskumar** [comment]
@antonagestam we have taken care of this in #199. Thanks to @ka7eh!

**Comment by antonagestam** [comment]
:+1:
