### ISSUE TITLE
Deleting all migrations and starting over throwing errors

### ISSUE THREAD

**Issue by the1plummie** [pydanny/cookiecutter-django#1933]
## What happened?
I'm trying to delete all migration files and starting over.  But I'm getting this error when running makemigrations:
```
django.db.migrations.exceptions.NodeNotFoundError: Migration socialaccount.0001_initial dependencies reference nonexistent parent node ('sites', '0001_initial')
```

**Comment by luzfcb** [comment]
@the1plummie 

1 - What do you mean by `Deleting all migrations`?

2 - What is the exact step by step you've done, from the project generation until you get the error?

**Comment by foarsitter** [comment]
You have deleted [contrib/sites/migrations/*](https://github.com/pydanny/cookiecutter-django/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/contrib/sites/migrations) whilst the project settings overrides the [contrib.sites migrations](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/base.py#L87). Either revert the deletion of the `contrib/sites/migrations/*` migrations or remove the `MIGRATION_MODULES` from your setting.

**Comment by browniebroke** [comment]
The answer provided by @foarsitter seems reasonable, I'm closing this as it doesn't look like an issue on our end.

**Comment by WhiskySoda** [comment]
I run into this problem frequency, the only way I have found to remedy this is to restore /contrib/sites/migrations/0001_initial.py from the git in order to preserve the migration history

**Comment by simkimsia** [comment]
For those who googled to this issue when they try to reverse the migrations in order to upgrade the django version, restore all the migrations in `/contrib/sites/migrations` and also restore all your initial migrations for all existing models and their dependency migrations is the safest way to go.

If the initial migrations of all your models and their dependencies have included certain libraries that need to be removed for your django upgrade, then you need to make those adjustments manually.

## Step by Step

0. If your database has data, I assume you know to back them up before making any changes
1. restore all your files associated wth the migrations in `/contrib/sites/migrations` and  initial migrations for all existing models and their dependency migrations. Delete the rest. Think of this collection of files as the baseline you cannot delete ever.
2. now i am assuming you have wiped your database at this point.
3. make adjustments on the baseline migration files. For e.g. you need to remove some library code that affected these migration files in some way because you no longer using that library.
4. run `migrate` on the baseline migration files 
5. run `makemigration to give you the fresh set of migration files
6. run your unit tests to make sure everything is okay. if not make further adjustments on the fresh set of migration files as needed
7. run `migrate` again as you wish
8. run your tests to make sure again
