### ISSUE TITLE
kubernetes with simply non-secure

### ISSUE THREAD

**Issue by elcolie** [pydanny/cookiecutter-django#1948]
## Description
`docker-compose.yml` is very handy. It helps me a lot to deploy my site in just a couple minutes.
Now I am preparing to scale my server up. AWS S3, CloudFront, and RDS are great. However, I don't want to rely on the single service. I wants to rely on myself.
I propose simple self-contained in the single cluster. 
1. Django
1. React/Angular
1. Ingress
1. Postgres
1. Minio
1. redis(Master & Slave)
1. rq
1. flower
1. celery

## Rationale
1. HA
1. Scaling

## Use case(s) / visualization(s)
High traffic request site

**Comment by browniebroke** [comment]
I'm sorry, but I don't understand what you suggest. I know what Kubernetes is, but I haven't got a chance to use it yet, maybe that's why. I'll try to ask a few specific questions:

1. You're listing several services, some of them not being part of `cookiecutter-django`. Are you suggesting to add them to the project? 
2. I've heard some good things about Kubernetes, but a common bad thing I hear is the complexity to get a cluster correctly configured. Many people using `cookiecutter-django` are not super familiar with Docker (at least that was my case a few years back). Introducing K8s would add more complexity they likely don't need.

Personally, I'd say I'm unlikely to accept a change to introduce K8s, but if it's added as an option to let users choose between K8S and docker-compose, maybe that could work... It depends on how much complexity it adds.

You're welcome to do the work in a fork, and worst case we could link to it for people interested.

**Comment by elcolie** [comment]
Good point!
Yes. Your understandings are correct. And configuration k8s is very difficult and complex.
I would like to see django deployment in the k8s easy like wordpress.

So best fit would be `helm`. Thank you for your response.

**Comment by ayushin** [comment]
so what about building a helm chart to support this?

**Comment by Afrowave** [comment]
I am interested in this suggestion and I agree with @browniebroke. This would need to be an option along side the Docker one.

I am just about to set up a project with k8s. I will look at how much woork it is and submit a PR. However, no proper timelines are in place.

**Comment by ayushin** [comment]
Lets continue in https://github.com/pydanny/cookiecutter-django/issues/2940

There are a few pointers there.
