### ISSUE TITLE
Kombu==4.4.0 breaks celery / redis implementation Docker

### ISSUE THREAD

**Issue by rich5851** [pydanny/cookiecutter-django#1954]
## What happened before?

Celery Workers started 

## What happens now?

kombu==4.4.0 released on the 3rd March 2019

Celery Workers fail to start with VersionMismatch
celeryworker_1  | kombu.exceptions.VersionMismatch: Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.6

Updating to redis 3.2 not an option as it causes django_celery_beat that I am also using to no longer change the periodic tasks file when tasks are updated.

## Steps to reproduce
Deployment local or production with docker
docker compose build and up

Fixed the issue by adding kombu==4.3.0 at bottom of requirements/base.txt

**Comment by rolep** [comment]
Then better to use kombu==4.4.0 cause 4.3.0 also has bug which I have encoutered: celery/kombu#1006
The bug is fixed in 4.4.0

Also am using django_celery_beat, but with database scheduler, seemingly with no such issues.

If using redis 2.x is preferred - then better stick with previous kombu version 4.2.xxx, but imho thats not in spirit of this project
