### ISSUE TITLE
Add support for reading settings from `.env` file.

### ISSUE THREAD

**Issue by theskumar** [pydanny/cookiecutter-django#197]
- It will allow to keep/and update local django settings, in a similar fashion we set environment variables on Heroku.
- If anyone move to custom dedicated server, they can still use `.env` file to store/read settings and use `fab` in combination of `dotenv` as list in advance usages to update settings on remote servers. 
- One step closer to 12-factor
- Apart from manually editing `.env` file. User can make use of command-line interface. 
- It is totally backward compatible way to dealing with settings. 

```
# basic usages
dotenv set DATABASE_URL postgres://myuser@mypassword:localhost/mydbname
dotenv set DJANGO_SOME_SECRET "this is top secret"
dotenv list
```

Thoughts?

**References**
- https://github.com/theskumar/python-dotenv

**Comment by slafs** [comment]
django-configurations will have this ability soon jezdez/django-configurations@01e3f5837f3d0fed215d

**Comment by theskumar** [comment]
:heart_eyes: wow! @slafs thanks for heads up. 

I think when this feature is available, we just need to update our read me.

**Comment by philippeluickx** [comment]
Trying to get this working nicely with integrating celery.
Issue at hand currently is that I need to run celery in my project folder to get it launched (not sure why, but otherwise my imports are messed up).
repo_folder/my_project
> celery -A celery_tasks worker -l debug
However, I typically launch my runserver command outside my project folder.
repo_folder
> python my_project/manage.py runserver

The complication here is that the path to my .env file (located on the same level as manage.py in repo_folder/my_project) is pointing to a different location depending on where I launch my command. In case of celery, it should point to ".env". In case of runserver, it should point to "my_project/.env"

I can work around this by making sure I always use the runserver command in my_project folder. If you have any better suggestions, I would gladly hear them!

Thanks!

**Comment by theskumar** [comment]
@philippeluickx let use know if using `__file__` magic keywords to get the absolute path of `.env` doesn't solve your issue. something like:

```
from os.path import join, dirname
dotenv_path = join(dirname(__file__), '.env')
```

adjust the path  as required at different places?

**Comment by philippeluickx** [comment]
Putting this in the manage.py works, but obviously not in the config files (as you would have to go one level up).
I do believe there is a good way to deal with this, however for the sake of moving forward I run all commands at project level again.
Thanks for the tip!

**Comment by tarkatronic** [comment]
I was able to implement this very easily on my own project, which is based on django-cookiecutter, and it appears to work with celery as well (at least, I can boot up the worker). I just added the following to `config/settings/common.py` right after instantiating `env`:

```python
try:
    env.read_env(ROOT_DIR.file('.env'))
except FileNotFoundError:
    pass
```
I'm fairly certain this will also work for the case of running manage.py from outside of the project folder.

**Comment by pydanny** [comment]
Closing this as I believe it's either been resolved or moot. Please reopen if that is not the case.
