### ISSUE TITLE
Unclear what paths to add to virtualenv

### ISSUE THREAD

**Issue by janfabry** [pydanny/cookiecutter-django#214]
It's not clear to me what paths should be added to the virtualenv. The contents of `setup.py` and `manage.py` seem to contradict each other.

For example, take the following project tree:

```
- repo_name/ # Alias: repo_dir
  - repo_name/ # Alias: project_dir
    - config/
    - manage.py
  - setup.py
```

Should `repo_dir` or `project_dir` be added to the virtualenv?

Given that there was a `setup.py`, I executed `pip install -e .` in `repo_dir`, and it added `repo_dir` as an egg link to my virtualenv. It also added `manage.py` as a script, so I could call it from anywhere - in theory, because it doesn't work from anywhere but `project_dir`.

This is because `manage.py` set `DJANGO_SETTINGS_MODULE` to `config`, which will only work from in `project_dir`. So I guess it should be `project_dir` that must be added to the paths? But what about the `setup.py`?

**Comment by theskumar** [comment]
Hey @janfabry, first of all thanks for bringing this topic to table. 

The confusion arrises because of the implicitly exposed PYTHON_PATH that point to `project_dir`[1], we have an internal discussion and the decision is made to expose only the top-level `repo_dir` in the PYTHON_PATH. Expect the changes very soon, which should resolve your concern above. 

Let me know, if anything else we can to solve the problem you are having.

[1] https://github.com/pydanny/cookiecutter-django/blob/e82cc8ba487a5e1142440b952edaac544210175f/%7B%7Bcookiecutter.repo_name%7D%7D/Procfile#L1
