### ISSUE TITLE
Upload large files in production leads to Gateway timeout error

### ISSUE THREAD

**Issue by uzi0espil** [pydanny/cookiecutter-django#2229]
## What happened?
Uploading a file with 500MB in local mode is working fine. But when I try the same file in production, django get restarted stating that worker timed out, the following docker messages printed:

```
django_1        | [2019-09-20 15:26:08 +0200] [384][CRITICAL] WORKER TIMEOUT (pid:384)
django_1        | [2019-09-20 15:26:08 +0200] [384] [INFO] Worker exiting (pid: 384)
django_1        | [2019-09-20 15:26:08 +0200] [1124] [INFO] Booting worker with pid: 1124]
```

I tried a smaller version of the same file and it works fine. I am using POSTman for uploading the file and it seems that this happens if the request took more than 30sec. I couldn't narrow down the problem whether it is from uWSGI or traefik. Hope can someone help me find out.

## What should've happened instead?
The request should take as much as it need until the file is uploaded and processed.

## Steps to reproduce
- Run in production mode `docker-compose -f production.yml up`
- Upload a file to django through API that might take more than 30 seconds to upload.

**Comment by pydanny** [comment]
Don't upload files this way to a Django server. Django's not designed to handle long connections like this, and will timeout, run out of server memory, or simply drop the connection. A better solution is to:
1. Upload the file to AWS s3, Google Storage, or the Digital Ocean equivalents.
2. Googling will reveal how to do this in a way that notifies Django when the upload is complete.
3. Upon notification of the upload, use Django (via Celery if you want to get fancy) to do whatever processing on the file that needs to happen.

In any case, this issue is out of scope for Cookiecutter Django.

**Comment by uzi0espil** [comment]
I am aware of such solution but it is not always applicable due to privacy for example. Nevertheless, the framework should be flexible, not restricting a user to only use a specific method or two. 

I agree that this might not be a problem of a Cookiecutter, but I still think that the framework should add a setting for modifying the request timeout.
