### ISSUE TITLE
How to connect then display PostgreSQL inside Docker with database GUI like DBeaver or TablePlus?

### ISSUE THREAD

**Issue by kwhandy** [pydanny/cookiecutter-django#2305]

**Comment by browniebroke** [comment]
By default, the `postgres` service doesn't expose any port externally. You can do it by [using the `ports` option](https://docs.docker.com/compose/compose-file/#short-syntax-1). Since the default port for PostgreSQL is 5432, you need to add these 2 lines to the `postgres` service in `local.yml`:

```
    ports:
      - "5432:5432"
```

You'll need to restart your stack for the change to take effect. 

If you have postgres running on your host machine, this might clash with it. In such case, I would recommend changing the port which is mapped on your host machine by changing the value to `"5433:5432"` for instance.

Then the credentials should be as follows:

- User: <same as POSTGRES_USER in .envs/.local/.postgres>
- Password: <same as POSTGRES_PASSWORD in .envs/.local/.postgres>
- Database: <same as POSTGRES_DB in .envs/.local/.postgres>
- Host/Server: localhost
- Port: 5432 (the number is before the ":" in the ports section of the `local.yml`)

I haven't tried

**Comment by browniebroke** [comment]
Closing this, feel free to comment if it doesn't work.

**Comment by bfssi-forest-dussault** [comment]
Alternatively, you can connect to the PostgreSQL container in DBeaver by running `docker inspect {container_id}` and grabbing the 'IPAddress' field and using that value for DBeaver's Host value instead of 'localhost'.
