### ISSUE TITLE
What is the purpose of the custom users app? 

### ISSUE THREAD

**Issue by tomdee** [pydanny/cookiecutter-django#232]
I can't find anything in the docs, so it's not clear that me that the extra complexity introduced by it is warranted.

**Comment by pydanny** [comment]
As a resource so we don't have to write this boilerplate each time we start a new project. While about 40% of the time I take it out because it isn't needed, the rest of the time it is quite useful.

If Windows allowed for Jinja2 logic in filepaths , I would have this as an option in `cookiecutter.json`. FWIW, some of the forks of this project remove this app.
