### ISSUE TITLE
Select django version  django 3.x or 2.x lts

### ISSUE THREAD

**Issue by scwall** [pydanny/cookiecutter-django#2515]
## Description

[//]: # (What's it you're proposing? How should it be implemented?)

The possibility to choose between django version 2.x **lts** or version 3.x
 
Example : 
```
Cloning into 'cookiecutter-django'...
remote: Counting objects: 550, done.
remote: Compressing objects: 100% (310/310), done.
remote: Total 550 (delta 283), reused 479 (delta 222)
Receiving objects: 100% (550/550), 127.66 KiB | 58 KiB/s, done.
Resolving deltas: 100% (283/283), done.
project_name [Project Name]: Reddit Clone
project_slug [reddit_clone]: reddit
author_name [Daniel Roy Greenfeld]: Daniel Greenfeld
email [you@example.com]: pydanny@gmail.com
description [Behold My Awesome Project!]: A reddit clone.
domain_name [example.com]: myreddit.com
version [0.1.0]: 0.0.1
timezone [UTC]: America/Los_Angeles
###################
Select django_version:
1 - 2.x lts
2 - 3.x
Choose from 1, 2,  [2]: 1
###################
use_whitenoise [n]: n
use_celery [n]: y
use_mailhog [n]: n
use_sentry [n]: y
use_pycharm [n]: y
windows [n]: n
use_docker [n]: n
use_heroku [n]: y
use_compressor [n]: y
Select postgresql_version:
1 - 11.3
2 - 10.8
3 - 9.6
4 - 9.5
5 - 9.4
Choose from 1, 2, 3, 4, 5 [1]: 1
Select js_task_runner:
1 - None
2 - Gulp
Choose from 1, 2 [1]: 1
Select cloud_provider:
1 - AWS
2 - GCP
3 - None
Choose from 1, 2, 3 [1]: 1
custom_bootstrap_compilation [n]: n
Select open_source_license:
1 - MIT
2 - BSD
3 - GPLv3
4 - Apache Software License 2.0
5 - Not open source
Choose from 1, 2, 3, 4, 5 [1]: 1
keep_local_envs_in_vcs [y]: y
debug[n]: n
```

## Rationale

[//]: # (Why should this feature be implemented?)

Version 2.x of django is a long term support version (2022), why not leave the possibility to choose between a version maintained for security and stability, maintainability or version 3.x. This also allows old applications that are not yet or will not be updated to continue running on new projects.

[//]: # ("Better to see something once than to hear about it a thousand times.")

**Comment by browniebroke** [comment]
> why not leave the possibility to choose between a version maintained for security and stability,

I'd say it's because of the maintenance overhead mainly. We already have a lot of moving parts in this template and maintinaing multiple versions of Django has historically been too much work. Arguabely, it might be easier to achive *right now* (because we just updated), but if we want to start using some Django 3.0 features now like ASGI, having Django 2 support somewhere would hold us back.

If you want to use a version supporting Django 2.2, you can checkout a specific tag using [the `--checkout` option from the cookiecutter CLI](https://cookiecutter.readthedocs.io/en/1.7.0/advanced/cli_options.html#cmdoption-c):

```
cookiecutter  https://github.com/pydanny/cookiecutter-django --checkout 2.2.6-01
``` 

As far as we're concerned, we aim to support a single version of Django.
