### ISSUE TITLE
An error occurred in the cookiecutter import template

### ISSUE THREAD

**Issue by 17864219845** [pydanny/cookiecutter-django#2602]
[root@bogon test]# /usr/local/python3/bin/cookiecutter git@github.com:pydanny/cookiecutter-django.git
You've downloaded /root/.cookiecutters/cookiecutter-django before. Is it okay to delete and re-download it? [yes]: no
Do you want to re-use the existing version? [yes]: yes
**A valid repository for "git@github.com:pydanny/cookiecutter-django.git" could not be found in the following locations:**
/root/.cookiecutters/cookiecutter-django

**Comment by luzfcb** [comment]
@17864219845 

To clone the repository using the **ssh** mode (`git@github.com:username/repository`) you probably require to generate the private/public key pair and include the public key on your GitHub account

Related documentation:
https://help.github.com/en/github/authenticating-to-github/checking-for-existing-ssh-keys

https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

https://help.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account



Another and more easy way is to use **https** instead of **ssh** to clone the repository.

```
cookiecutter https://github.com/pydanny/cookiecutter-django.git
```

or

```
cookiecutter gh:pydanny/cookiecutter-django
```



If the problem persists and since this problem is related to cookiecutter and not cookiecutter-django, please report the problem at https://github.com/cookiecutter/cookiecutter/issues

**Comment by 17864219845** [comment]
Thank you very much. I'll try to solve the problem
