### ISSUE TITLE
Gunicorn command not found when running dev server asynchronously.

### ISSUE THREAD

**Issue by arnav13081994** [pydanny/cookiecutter-django#2623]
## What happened?

During project generation, I had agreed to using async (use_async: y), but when I tried to run my local Django dev server asynchronously, I got the following error:

> zsh: command not found: gunicorn

The fix was as simple as installing gunicorn requirement listed in production.txt

## What should've happened instead?

My expectation was to be able to run the server asynchronously even in dev because I want to have my dev and prod environments as close to each other possible. But I'm guessing there might be a good reason why the choice was made to explicitly add gunicorn only to production.txt and not to local.txt

## Steps to reproduce

[1]: # Follow steps 1-7 on the official documentation for [local dev](https://cookiecutter-django.readthedocs.io/en/latest/developing-locally.html) 
[2]: # Run the following line:
```
gunicorn config.asgi --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker --reload
```
And notice the error 

> zsh: command not found: gunicorn

[3]: # Mac OSX 10.15.5, using pycharm 2020.1 Pro, Python 3.8.0, Postgresql 12.3.

## Potential Solution

The following line should be added to base.txt:

```
{%- if cookiecutter.use_async == 'y' %}
uvicorn==0.11.5  # https://github.com/encode/uvicorn
gunicorn==20.0.4  # https://github.com/benoitc/gunicorn
{%- endif %}
```

And then the gunicorn requirement can safely be removed from production.txt

**Comment by Andrew-Chen-Wang** [comment]
Perhaps you're using an old version @arnav13081994.

Try this command (in the master branch in compose/local/django/start):

`uvicorn config.asgi:application --host 0.0.0.0 --reload`

(Note: I added the commits for async. If you have any questions about async, let me know! You should know that you SHOULD NOT use Gunicorn in local development. Please use uvicorn only).

**Comment by arnav13081994** [comment]
Thanks for your reply, @Andrew-Chen-Wang.

Is there any resource you can share with me that goes into why one should run Uvicorn over Gunicorn locally? I tried finding it online but didn't really get anything good or reliable. Or even best practices for running an asynchronous local Django development Server. That would be of immense help to me!

Also, the command I mentioned earlier, is in the [latest version](https://cookiecutter-django.readthedocs.io/en/latest/developing-locally.html) of the official documentation for running an Asynchronous Local Django Development Server. Maybe the documentation hasn't been updated?

**Comment by Andrew-Chen-Wang** [comment]
Ah sorry about the docs. This repo is just not getting updated very much, and attention to detail is getting less fine (especially on my part regarding implementing async capabilities).

Running uvicorn is better than running gunicorn since we're using Uvicorn's internal reloader process which we added with the recommended watchgod's package. If we used gunicorn, then we wouldn't get this. (We use watchgod mostly because of the reason in #2575).

Best practices... Well before I go into blabbering mode, there really isn't many best practices. I'm supposed to start a repo for Django async best practices, but I haven't experimented with async views too much yet. And the thing is... async views are not going to work too well because zero ORMs are async capable.

Blabbering: One part of my mini-project life is getting Django more async capable through helping the psycopg3 project for an async Django ORM and pushing for more people to use native websockets instead of Django channels since I like a one-user-per-socket motto (only works on non-browser though since if you go to a different page, you drop the socket connection).

Really, the one thing that makes async appealing for me is the websockets. Decreases HTTP traffic which in turn decreases costs significantly, server side and client side through reduced payload (and AWS charges a lot for payload).

**Comment by arnav13081994** [comment]
@Andrew-Chen-Wang Thanks! And yes I agree with you on that. In fact, I was facing some weird issues running uvicorn with gunicorn with https. I will switch to your recommendation for now.

Thanks you your help!

**Comment by Andrew-Chen-Wang** [comment]
@arnav13081994 Np! Running gunicorn with uvicorn locally probably won't work if you don't have a certificate (you automatically get one if you dockerize with Traefik). You can close the issue if you'd like.

**Comment by arnav13081994** [comment]
@Andrew-Chen-Wang Thank you for your help. Yes you are right about SSL. I just used [mkcert](https://github.com/FiloSottile/mkcert) to run the dev server with SSL. And it also doesn't throw annoying warnings like runserver_plus either. I ended up passing path to certs generated by mkcert to runserver_plus to get around both those issues. Abandoning async for now till there can be DB ORM support for async.

Once again thank you for your help. Closing this issue.
