### ISSUE TITLE
Missing /favicon.ico from admin in production

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [pydanny/cookiecutter-django#2746]
## What happened?

Production admin panel tries to get /favicon.ico from your domain.
This results in a BROKEN INTERNAL LINK error. This only happens in the admin. But the favicon does appear.

## What should've happened instead?

Use the favicon in static.

## Steps to reproduce

Deploy on well anywhere. On the initial GET request, the error will pop up. Later on, it won't show up anymore.

An email from my server:

```
Referrer: https://donate-anything.org/admin_url/login/?next=/admin_url/
Requested URL: /favicon.ico
User agent: ~~censored~~
IP address: I believe my current ALB
```

This isn't logged in Sentry for some reason. Maybe we can include a redirect?

**Comment by browniebroke** [comment]
I think nothing is reported in Sentry because it's not a real 500 error, it's an email sent by this middleware:

https://github.com/pydanny/cookiecutter-django/blob/ebd43bbd3c29ff29cdf2617e661b857b89eb520c/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/base.py#L150

**Comment by Andrew-Chen-Wang** [comment]
Oh wow I didn't even see that. Thanks! What if someone spammed a random endpoint, would it still generate emails? Probably still have emails sent. Closing this anyways.

**Comment by browniebroke** [comment]
I think it would be nice to fix the broken favicon. If it's not feasible and the middleware is too spammy, we could remove it.

**Comment by Andrew-Chen-Wang** [comment]
Middleware is definitely spammy. Been awhile since I've deployed, so I was surprised to get emails about 404s to php endpoints, random api/jsonws/invoke endpoints (so bots looking for exploits), etc..

Regarding the favicon, my solution was a simple RedirectView as follows:

```python
path("favicon.ico/", RedirectView.as_view(url=f"{settings.STATIC_URL}images/favicons/favicon.ico"))
```
I didn't actually implement it though because a. I disabled the email middleware and b. the favicons always showed up. I wonder if the browser was just prefetching for a `/favicon.ico` endpoint because I don't see the Django admin templates looking for the /favicon.ico endpoint in the sources tab of my browser's dev tool console. (This prob doesn't seem to be a bot; happens when I initially go to the admin page).

I think for the middleware, it might be useful to have a TODO rather than deleting it so actual broken links can be found. Although it definitely can get spammy fast.

**Comment by BoPeng** [comment]
Found this ticket with a bunch of emails for missing `/favicon.ico` and `/wordpress`. Upon [further looking](https://docs.djangoproject.com/en/3.2/howto/error-reporting/
), it appears that 

```python
import re
IGNORABLE_404_URLS = [
    re.compile(r'^/favicon\.ico$'),
]
```
may be a better solution.

**Comment by Andrew-Chen-Wang** [comment]
Hm it doesn't really resolve the issue of spam though. Especially since many devs use the django-allauth package when using cookiecutter-django, and thus the email sending functionality, devs are sure to use some kind of paid email service.

I really hate seeing trolls waste people's money, so simple `/.env`, `/.php`, `/r`, `/firebase.json`, etc. endless endpoints will make everyone new to this middleware surprised. I think removing the middleware is the better option. Maybe adding it in `settings/local.py` is fine, but prob not for prod.

**Comment by BoPeng** [comment]
The middleware serves its purpose and I do not want to remove it completely. That is to say, if some URL on my website is actually not accessible, I want to know about it.

Then there are two types of annoynances. `/favicon.ico` is a legitimate request from browsers and we should try to handle. However, as far as I can tell, 

 ```html
 <link rel="icon" type="image/png" sizes="16x16" href="{{ static('images/favicon.png') }}">
```
provided by the cookiecutter does not prevent the  `404` error. Some [suggested](https://stackoverflow.com/questions/21938028/how-can-i-get-a-favicon-to-show-up-in-my-django-app) using

```html
<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
```
but others say `shortcut icon` is deprecating. The idea of

```python
 re_path(r'^favicon\.ico$', favicon_view),
```
just does not look right. So, compared to these solutions, using `IGNORABLE_404_URLS` to prevent the middleware from sending out email for this particular URL makes sense to me.

Then there are trolls and robots that probing every website which has caused emails for `/wordpress/` etc. You could remove the middleware altogether because of them, but I will simply add them to `IGNORABLE_404_URLS`.
