### ISSUE TITLE
Rename the DATABASE_URL environment variable to DJANGO_DATABASE_URL

### ISSUE THREAD

**Issue by lgp171188** [pydanny/cookiecutter-django#299]
When every other environment variable used in this cookiecutter template has a ``DJANGO_`` prefix, it seems to be ambiguous to have the environment variable for database URL as ``DATABASE_URL``. This would make all the environment variables referenced in the settings module to start with ``DJANGO_`` prefix. Your thoughts on this @pydanny ?

One thing to consider is that making this change involves very little code change, but to do it without breaking backward compatibility requires a bit more care.

**Comment by luzfcb** [comment]
This project has been designed to run on Heroku platform. (ok, it works without or almost without modification on other platforms.).

Heroku automatically creates a variable named environment of `DATABASE_URL`.
In a typical production environment, you only have a single database, and this configuration makes it simple and predictable. If you add more database in your application in Heroku, Heroku automatically creates a variable named environment `HEROKU_POSTGRESQL_COLOR_URL` where COLOR is a random color defined by heroku. Then we would have a environment variable different and not predictable.

Due to this fact, it is not possible to rename `DATABASE_URL` to `DJANGO_DATABASE_URL`

this is one case where the following applies stretch of [PEP 20](https://www.python.org/dev/peps/pep-0020/)
```
..
Although practicality beats purity.
..
```

If you've seen some confusing thing in the documentation of this project, feel free to propose improvements.

See more information about Heroku database configurations:
[1] https://devcenter.heroku.com/articles/heroku-postgresql#establish-primary-db
