### ISSUE TITLE
Front-End Dependency Management

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#301]
Right now any kind of front-end dependency like Bootstrap, Angular, or whatever else we use is manually imported into the project. What about using one of the common front-end tools instead?

**Comment by luzfcb** [comment]
the last approach I saw was this: 
http://owaislone.org/blog/webpack-plus-reactjs-and-django/
https://github.com/owais/django-webpack-loader

**Comment by andresgz** [comment]
What about to manage those front-end dependencies using Bower? In that way I can handle that with a bower.json.

If I want Angular, I would  need to execute:

    bower install angular

The tricky part would be to make Bower able to inject those dependencies after the bower install.

**Comment by pydanny** [comment]
Considering #616 can I close this issue?

**Comment by ssteinerx** [comment]
@pydanny I think this is a completely different thing.  This is talking about using e.g. webpack or bower to manage dependencies.  So, for example, if you select "Use Bootstrap" during project generation, the dependency would be injected into the bower/webpack/etc. config file rather than being pulled in manually.  This is a whole 'nuther kettle of fish than just pinning dependencies and really needs its own discussion/project (under Project Organization).
