### ISSUE TITLE
Local Dev Missing Raven

### ISSUE THREAD

**Issue by CharlesBergmeier** [pydanny/cookiecutter-django#302]
When creating a project with Raven (Sentry), local dev fails when following the instructions to run the server:

```bash
    from raven.contrib.django.raven_compat.middleware.wsgi import Sentry
django.core.exceptions.ImproperlyConfigured: WSGI application 'config.wsgi.application' could not be loaded; Error importing module: 'No module named 'raven''
```

The issue is Raven is added to the `wsgi.py` file across all environments:
https://github.com/pydanny/cookiecutter-django/blob/d65f2bde6d9c8cd8a427d8ea640130d08442704a/%7B%7Bcookiecutter.repo_name%7D%7D/config/wsgi.py#L22-L24

But the requirements file only adds raven as a dependency in production:
https://github.com/pydanny/cookiecutter-django/blob/d65f2bde6d9c8cd8a427d8ea640130d08442704a/%7B%7Bcookiecutter.repo_name%7D%7D/requirements/production.txt#L22-L26

Which leaves local dev broken, due to the missing dependency.

I actually like the pattern of not including Raven in local dev, but I'm not sure how to keep the import and wrapper for application out of `wsgi.py` without some sort of settings.env check.  Thoughts?

**Comment by jayfk** [comment]
I agree, raven should not be loaded on development. Otherwise your sentry server gets all the error messages you encounter during development, that makes no sense.

The current implementation gets it right at the settings part (raven only added in production), but as you noted `wsgi.py` is the problem here.

Two possible solutions:

* Use a config switch with `if os.environ.get("DJANGO_SETTINGS_MODULE") == "config.settings.production"` like [here](https://github.com/jayfk/cookiecutter-django-docker/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/config/wsgi.py) with newrelic.
* a try catch block that loads the right wsgi application

**Comment by yunti** [comment]
Created a quick pull request for this. Not sure how to directly attach it to this issue rather than raising a new issue. Still getting used to github :)

**Comment by jazztpt** [comment]
I also got an import error in the taskapp related to raven not being loaded on development.  PR coming.

**Comment by jayfk** [comment]
thanks to @yunti @sdonk and @jazztpt for fixing this.
