### ISSUE TITLE
Consider removal of dev.yml

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#308]
As we have `docker-compose.yml`, is there a need for `dev.yml`?

Ping @jayfk

**Comment by jayfk** [comment]
Yes, since `docker-compose.yml` comes with all the bells and whistles and the application code baked into the container. That makes development a pain because you have to rebuild on every code change.

`dev.yml` on the other hand is considered for development with a stripped down stack and, more importantly, the code is mounted from the host filesystem into the container. That allows hot code reloading of `runserver` without rebuilding the entire stack.

**Comment by pydanny** [comment]
Okay, I'll probably document this in the next few days.

**Comment by pydanny** [comment]
@jayfk What are your thoughts on moving `dev.yml` into the `compose` directory? Seems to me that's a great place to put existing and other future `docker-compose` configuration YAML files.

**Comment by jayfk** [comment]
I'm afraid this won't be possible at the moment. `Dockerfile`s and docker-compose configuration files work on relative paths, BUT you can't walk back a directory.

In case of `Dockerfile`s this has something to do with what gets send to the docker deamon to build an image. There are workarounds available where you `tar` the directory and then add it, but that's relatively ugly.

There are open issues all over the place for this so I hope we'll find a solution for this in the foreseeable future.

**Comment by jayfk** [comment]
I came to think if we might switch the naming. `docker-compose.yml` is meant to be as a starting point for a deployment, but a new user might think otherwise.

I'm always sticking with the scheme to run the default file on prod, so that I never start a dev environment on a production server in case I forgot to add the `-f` switch or the environment variable. 

While this is a valid safety measure, one could argue that it's not very friendly for new users. Changing `docker-compose.yml` to `staging.yml` and `dev.yml` to `docker-compose.yml` could be the better idea.

There's some [documentation](https://github.com/pydanny/cookiecutter-django/blob/master/README.rst#getting-up-and-running-using-docker) for it in the *how to get started* section.

**Comment by jayfk** [comment]
We might be able to do it all in one file soon: https://github.com/docker/compose/issues/1784

**Comment by stepmr** [comment]
I might have a chance to look into this shortly, compose's extends functionality is now fully documented: https://docs.docker.com/compose/extends/

**Comment by jayfk** [comment]
Addressed in #516
