### ISSUE TITLE
stability of bootstrap 4 alpha

### ISSUE THREAD

**Issue by yunti** [pydanny/cookiecutter-django#316]
On the recent changes to bootstrap 4 alpha - we seem to have removed bootstrap 3 and be using bootstrap 4 alpha only.  Just questioning if there is a rollback to be included if not using bootstrap 4.  (I'm assuming that cookiecutter-django  is aimed at production ready deployment which obviously doesn't fit with the 4 alpha state).

Thanks

**Comment by pydanny** [comment]
Hi @yunti, cookiecutter-django often explores the bleeding edge. Hence why we moved to Bootstrap 4 Alpha, and why we sometimes explore different architectural patterns. What's interesting is that the changes to our `base.html` were minimal and forms (powered by django-crispy-forms) continue to work. What this means is if you want to remain with Bootstrap 3, the edits to `base.html` are quite easy.

**Comment by yunti** [comment]
Thanks good to be clear on how it's used (i.e. more bleeding edge than conservative production). As you mentioned it's not much to change.  Thanks for the feedback and sorry for raising an unnecessary issue.

**Comment by pydanny** [comment]
Hi @yunti, you would be surprised by how many conservative production minded people want us to be using bleeding edge stuff. :wink: 

Also, there are no unnecessary issues. Please, don't feel constrained in asking questions or raising issues.

**Comment by yunti** [comment]
I can well believe it - the temptation of being on the cutting edge is too much some times.

Thanks for your comment regarding issues, I really appreciate, particularly as I’m currently finding my way round open source development etiquette.

I was curious as to why you went for the separate base,local, prod settings (and requirements) file approach rather than say django-configurations. Is either fine for best practice or does django-configurations have issues in some areas?

**Comment by luzfcb** [comment]
Previously, django-configurations was used in this project, see tag [1.6.6](https://github.com/pydanny/cookiecutter-django/tree/1.6.6/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D/config), but with the release of Django 1.8, Jezdez was too busy to solve problems on non paid projects ( and I understand, because I have not figured out a way to support my family only from sunlight ), https://github.com/jezdez/django-configurations/issues/105#issuecomment-88895512 .

After that, @theskumar suggested the alternative that is being used now. This solution has simplified things, to let the settings closest to the configuration generated by django startproject and also uses an approach based on [Twelve Factor methodology] (http://12factor.net/) and because Heroku use that ...

let django-configurations, eventually solved these problems https://youtrack.jetbrains.com/issue/PY-12443 https://youtrack.jetbrains.com/issue/PY-11429 https://youtrack.jetbrains.com/issue/PY-16530 

The explicit separation of test configurations, development(local) and production + environment variables prevents you inadvertently put in a git repository (or other) data that should not be easily accessible, such as passwords.

Also for this reason, it is not interesting to have, for example, django-debug-toolbar in a production environment because it may end up revealing too much information of your system, and make life easier for malicious users, and some tools used in the development environment can also decrease the performance of your site.

The [Zen of Python](https://www.python.org/dev/peps/pep-0020/) say ``Explicit is better than implicit``. I think this approach is sufficiently explicit, but not enough to be complicated.

Additionally, I think the practice of "explicit is better than implicit", could be used for other things besides code ... maybe life would be a little easier (or not :smile_cat: )...

I have my personal rule, always try to be cordial with people, irrespective of the level of knowledge, color, race, sexual orientation, religion ... Life is short enough and complicated enough for me to lose my precious time with useless discussions.

ps.: my english is bad, excuse me for possible failures of concordance in the text ...

**Comment by pydanny** [comment]
To reinforce @luzfcb, one of the issues that we faced with having just one settings module was that it became huge, unwieldy. When a module gets over 1000 lines of code I get nervous on principal, so I was never quite happy with our old single settings module.

When @theskumar suggested migrating to a multiple file approach I thought about it long and hard. Finally I focused on these three lines from the Zen of Python:

```
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
```

Conclusions:

1. On readability, the single module was so large it was hard to mentally parse. It wasn't readable, unless you can remember all the bits and pieces, which most of us cannot with a huge file. Which suggested that maybe we should break it up.
2. 12 Factor insists on single settings modules and breaking this would be a special case. Which breaks the rules, right?
3. Practically speaking, in real world deployments the single settings module was a pain. Fortunately for us, 12 Factor is a practice, not a law. So we consciously broke the practice a little bit, in the name of practicality.

**Comment by pydanny** [comment]
I also agree with @luzfcb, life is short. Open source etiquette in my opinion is about being cordial to one another, no matter their background (I heartily subscribe to https://www.djangoproject.com/diversity/). As long as we remain cordial we can talk plainly and openly. Let us not be afraid to ask any question, no matter how small or how large.

Glad to have you in the open source world @yunti. :smile:

**Comment by jayfk** [comment]
> I have my personal rule, always try to be cordial with people, irrespective of the level of knowledge, color, race, sexual orientation, religion ... Life is short enough and complicated enough for me to lose my precious time with useless discussions.

Absolutely, you forgot the gender. I'm sure you've already seen it, but for everyone stumbling across this you should watch the excellent talk from @olasitarska and @asendecka on EuroPython 2015 https://www.youtube.com/watch?v=DUgYznUfwyo
