### ISSUE TITLE
Rollback django-stubs to 1.5.0 for pycharm projects

### ISSUE THREAD

**Issue by kanusek** [pydanny/cookiecutter-django#3192]
## Description
The problem I'm having is with Pycharm failing to provide predictive text when using the ORM filter function.

I have multiple projects that were generated a few weeks apart and they have different versions of this library [django-stubs].

My older project using django-stubs 1.5.0 is working fine.
My newer project using django-stubs 1.7.0 does not provide predictions

What are you proposing? How should it be implemented?
If Pycharm is selected during scaffolding, use django-stubs 1.5.0 until the problem has been solved.

## Rationale

Why should this feature be implemented?
Pycharm's predictive text is a huge time saver and new users that don't know of it's existence have no idea what they're missing! 

Thanks. You all are awesome!

**Comment by kanusek** [comment]
Yes, I rolled it back on my project but I wanted to share this incase someone else was having an issue.

**Comment by luzfcb** [comment]
@kanusek This project currently uses `django-stubs` 1.8.0 since April 12. 
The `django-stubs` 1.8.0 version should use with` mypy` `0.812`.

Can you please update both on your project and test if it works as expected?
Remember, after updating them, force Pycharm to regenerate the caches by clicking on the menu `File` -> `Invalidate Caches`

**Comment by kanusek** [comment]
It must be something else... I tested it on my new project and it's still having problems. My older project still worked after updating to those version. I appreciate the suggestions. It's probably just my project collecting dust.
