### ISSUE TITLE
Mobile navbar doesn't expand nicely

### ISSUE THREAD

**Issue by audreyr** [pydanny/cookiecutter-django#325]
When collapsed, it looks fine:

![screen shot 2015-09-13 at 9 31 04 am](https://cloud.githubusercontent.com/assets/74739/9837623/59fb16ea-59fa-11e5-96a0-9684e49a94e2.png)

When expanded, it doesn't look right:

![screen shot 2015-09-13 at 9 32 47 am](https://cloud.githubusercontent.com/assets/74739/9837624/6c05305a-59fa-11e5-864f-f910d209b2fa.png)

Each link should be on its own line, like this:

![screen shot 2015-09-13 at 9 33 40 am](https://cloud.githubusercontent.com/assets/74739/9837626/8d9d89ce-59fa-11e5-85e7-4f2994ff2d6c.png)

**Comment by jayfk** [comment]
Almost there:

<img width="392" alt="screen shot 2015-09-17 at 22 59 10" src="https://cloud.githubusercontent.com/assets/2930472/9945826/eaa29fa4-5d8f-11e5-8702-3cd445868159.png">

The only problem remaining is that the brand has to dissapear on desktop because it has to be surrounded by a `clearfix` to work on mobile * *sigh* *

<img width="828" alt="screen shot 2015-09-17 at 22 59 21" src="https://cloud.githubusercontent.com/assets/2930472/9945820/e7681bc0-5d8f-11e5-8d91-2dc843b63318.png">

If your willing to pick this up where I left, I will create a WIP PR. Otherwise I'll pick this up next week.

**Comment by audreyr** [comment]
That's awesome @jayfk. If you send a WIP PR, I can try to take a stab at the rest.

**Comment by jayfk** [comment]
Had some spare time today and finished it.
