### ISSUE TITLE
REDIS_URL vs DJANGO_CACHE_URL

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#379]
Here's a glitch:

1. In `config.settings.production.py`, we specify `REDIS_URL`.
2. In `compose/django/entrypoint.sh`, we specify `DJANGO_CACHE_URL`.

This is a conflict. `REDIS_URL` is a Heroku-ism, but on the other hand `DJANGO_CACHE_URL` might be too specific. I'm tossing this into @jayfk's court for the first pass at an answer to what value we should set and where.

**Comment by jayfk** [comment]
That's a hard one. I prefer `DJANGO_CACHE_URL` because it describes the service (cache), not the product that is used (redis). Cookiecutter used this before 613b91d71e14639ca2cc514aa2473a9f5db09871. I believe that's the reason why the naming is not consistent here.

But I really have no strong opinion here, both are fine. If `REDIS_URL` works on heroku out of the box, then let's stick to it.
