### ISSUE TITLE
config/settings/common.py - LOGIN_URL

### ISSUE THREAD

**Issue by thornomad** [pydanny/cookiecutter-django#386]
In common.py we have:

    LOGIN_URL = 'account_login'

But it seems the actual URL would appear to be  '/accounts/login/' from the allauth.urls.

**Comment by Eraldo** [comment]
Yes, @thornomad .. the actual url is by default '/accounts/login/'.
In order to avoid hard-coding (https://en.wikipedia.org/wiki/Hard_coding)
This url has a name attached with which it can be referenced: 'account_login'
You can take a look at the source: 
https://github.com/pennersr/django-allauth/blob/master/allauth/account/urls.py
(as of current master: line 8)

So that should get the right url and make it possible to customise/update the url-path.
Is that understandable?

**Comment by thornomad** [comment]
Oh! So you are using LOGIN_URL to reference the URL "name" that would be used with 'reverse()' ? I see.  

https://docs.djangoproject.com/en/1.8/ref/settings/#login-url

I didn't realize it could be used that way!  I will just reverse() it then. 

Thanks.
