### ISSUE TITLE
Error on installing pillow 

### ISSUE THREAD

**Issue by FailSafe86** [pydanny/cookiecutter-django#427]
received this error when trying to install requirements/local.txt

ValueError: --enable-jpeg requested but jpeg not found, aborting.

issue solved by installing libjpeg-dev
http://stackoverflow.com/questions/32942861/error-installing-pillow-on-ubuntu-14-04
sudo apt-get install libjpeg-dev

**Comment by luzfcb** [comment]
all non-python dependencies to Ubuntu 14.04 are described here: [requirements.apt](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/requirements.apt)

This small utility ([install_os_dependencies.sh](https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/install_os_dependencies.sh)) helps you install them

run
```bash
sudo ./install_os_dependencies.sh install
```

said that, it is not documented, I accept gladly help to documenting this, because I have not had free time to do it

**Comment by FailSafe86** [comment]
awesome!...documentation didn't mention this and it would have saved me time faffing around. So, I don't mind documenting this...just show me how and where you want it

**Comment by luzfcb** [comment]
probably this is the best place : https://github.com/pydanny/cookiecutter-django/blob/master/docs/developing-locally.rst#getting-up-and-running-locally
