### ISSUE TITLE
Sharing docker containers with other team members

### ISSUE THREAD

**Issue by danielgamble** [pydanny/cookiecutter-django#458]
Probably isn't 100% related to `cookiecutter-django` specifically but i just followed: https://realpython.com/blog/python/development-and-deployment-of-cookiecutter-django-via-docker/

Which went real well and am thinking of using this as my base for future projects, just 1 question though. Say if i'm working on a development team, what is the ideal workflow for sharing dev & production containers with other members of the team?

**Comment by jayfk** [comment]
What do you mean by "sharing containers"?

There's no need to do that. Every person in your development team builds his/her own containers based on the Dockerfiles in your repository.

Or do you mean the data from e.g. postgres?

**Comment by danielgamble** [comment]
Well at the moment we provision a DO droplet and everytime we want to update, we git push then run our update commands that do that. I was curious how that kind of workflow works when you have a container that is based on DO and everyone can update the same container. I apologise this is my 1st time looking at Docker :)

**Comment by jayfk** [comment]
What you call *container based on DO* is just a droplet that runs the docker deamon. Docker Machine makes it easy to communicate with the deamon via the command line, but it's really just a ubuntu box running docker.

If you want to share that with your team, you just have to export the files in `.docker/machine/name`. When it comes to deployments I prefer to install the OS and docker myself and run the docker commands directly on the box.

**Comment by burhan** [comment]
A docker container is a _running instance_ that is based from a _docker image_.  You can think of a docker image as a "read only" version of a docker instance.

A dockerfile builds a docker image that is pre-configured, then you run it (and it becomes an image), Since docker images are read-only, generally they are packed with only the core files that are required for that docker to run - they don't contain any _runtime files_ (like say logs or temporary data), and in the case of application servers - like say Apache or nginx, it doesn't contain the HTML documents or content.

For us, we are providing docker containers that are pre-configured to run django (along with all the dependencies). The dockers are linked with your workstation so that when the image is running, it has access to your django project.

You would normally share just the dockerfile, which contains information on how to create the server, and how to link it with the source.

The dockerfile is configured so that when the image runs, it looks for content at a specific path, which is configured in the dockerfile to be mapped to the source code. This source code is often subject to version control.

Anyone with the dockerfile can run the exact same application on their laptops; if multiple people need to share access to one instance - then you can run the docker image on a third party server (like a droplet), then to update the code - just do `git pull` on the droplet.

You can also - and many people do this - build an image that includes all your data and source code; this way all the other person has to do is download the image and run it. This makes changes difficult as after each change, you have to rebuild the docker image to "save" them.

Hope this helps.

**Comment by jayfk** [comment]
I think this can be closed now, excellent explanation @burhan.
