### ISSUE TITLE
Lets Encrypt

### ISSUE THREAD

**Issue by jayfk** [pydanny/cookiecutter-django#471]
Lets Encrypt is in public beta since a couple of weeks and it would be nice if we could document a way for people to use it
- [x] on docker
- [ ] on heroku
- [ ] on ubuntu

Personally, I don't like the official client because it does too much. [simp_le](https://github.com/kuba/simp_le) looks promising.

Any thoughts? Is someone already using Lets Encrypt on a side project?

**Comment by pydanny** [comment]
:+1:

**Comment by burhan** [comment]
Docker support is already available; since all it does is export the paths with the certs and keys; as per the [docs](https://letsencrypt.readthedocs.org/en/latest/using.html#running-with-docker); so that part is done.

For heroku the process is a bit more involved; I am playing with this right now to see how it can be automated.

For Ubuntu (this is next on my list to try) - the process should be very similar to that of docker.  The key point being you have to manually extract the ACME key and create the end point for it - as typically you do not run the commands directly on your production servers.

I can cook up something for this.

**Comment by MathijsHoogland** [comment]
Good idea! As a beginner I also already managed to set this up on a private project, promising technique! As a docker beginner I haven't tried it on my cookiecutter-django project yet, we should also describe how to setup some sort of auto renewal function since the certificates are only valid for (3?) a short period of time.

**Comment by mjsisley** [comment]
I have this setup with Docker (changes to docker-compose and nginx config) and think it would be a great addition to the project.

I could submit a PR that offers automatic letsencrypt support as long as Docker is chosen. 

@jayfk What is the opinion of the core maintainers on adding support incrementally by development/ deployment method?

**Comment by pydanny** [comment]
@chrisdev was working on this today at the Cookiecutter sprints at PyCon. Perhaps @chrisdev and @mjsisley could collaborate together?

**Comment by jayfk** [comment]
> @jayfk What is the opinion of the core maintainers on adding support incrementally by development/ deployment method?

I think that's the best way :). We won't find a solution for all kinds of deployment methods over night.

I've used Caddyserver in the past that has built in letsencrypt support. If someone is working on this, take a look at:

 * Caddyfile https://github.com/pydanny/djangopackages/blob/dockerize/compose/caddy/Caddyfile
 * Dockerfile https://github.com/pydanny/djangopackages/blob/dockerize/compose/caddy/Dockerfile

**Comment by toanant** [comment]
Lets Encrypt already launched their official client [certbot](https://certbot.eff.org) with automated as well as advanced installation doc for different web-server and operating system.

**Comment by jeffcjohnson** [comment]
For Heroku I used https://github.com/dmathieu/sabayon and it worked great.
