### ISSUE TITLE
Make Docker and Heroku cookiecutter.json options?

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#474]
Here's the thing, both deployment methods leave a lot of stuff all over the generated file structure. That's fine, but if you don't need one of them, then those files are just chaff. While many of us old timers know which files can be safely removed, not everyone has that knowledge.

I'm thinking that all we need is to add some more logic to the `post_gen_hook` to manage the files. If you choose Docker, then the Heroku stuff is nuked. If you choose Heroku, then the Docker stuff is deleted.

Thoughts?

**Comment by niklasae** [comment]
Cleaning up is always a great idea. But just to be clear, you are only talking about the production environment here? So we would still be able to create projects where we could develop on Docker and deploy to Heroku?

**Comment by jayfk** [comment]
> Cleaning up is always a great idea. But just to be clear, you are only talking about the production environment here? So we would still be able to create projects where we could develop on Docker and deploy to Heroku?

I can't speak for @pydanny, but I think the idea is to make both optional. You'd be asked if you want to `use_heroku` and `use_docker` and if you answer both with `y`, you'd get a working docker environment and the files needed to deploy to heroku.

**Comment by yunti** [comment]
I think that's a very good idea.  Generally I think heading in the direction of having different configurations as cookiecutter options  (as we have done with python2/3. new relic etc.....) with cleaner output is preferable rather than having both included by default (with some pruning required afterwards).    Although I wouldn't make an option for every configuration but for those options that require quite a bit of configuration and Heroku v Docker is a good example,  it seems like a good idea.  

I would suggest making the default (for this and any other future cookiecutter options) the simplest one (here Heroku), so that any new user can just select the standard defaults and have a good starting point.

**Comment by jayfk** [comment]
As @niklasae has mentioned, I wouldn't look at these options as if the one would nuke out the other.

You might have a project where you want to use docker during development and heroku on production. Or you want to share a project you are working on very fast and want to deploy to heroku first, but want to switch to docker later.

From this point of view it makes more sense to make both optional so that they can be mixed.

**Comment by pydanny** [comment]
I like @jayfk's idea that you can have either option or both. It will take some work in the `pre_gen_hook` or `post_gen_hook`, but nothing too challenging.

**Comment by yunti** [comment]
@jayfk Good point I hadn't considered that it could be useful to have both for exactly that scenario you mentioned.  One or the other or both sounds ideal.

**Comment by valerymelou** [comment]
That will really improve the template. I'm just starting a fork of the project just because I don't often use Docker or Heroku or event Grunt and I don't like the way their files pollute my development environment.

**Comment by noisy** [comment]
:+1: for `use_heroku` and `use_docker`.

**Comment by jayfk** [comment]
These are now optional :)
