### ISSUE TITLE
Installation instruction for Ubuntu needed

### ISSUE THREAD

**Issue by sakhmedbayev** [pydanny/cookiecutter-django#512]
First of all, let me thank authors and contributors of this project. It seems that you are doing a lot to make life easier for people like me, who are newbie to django.

I have tried to install cookiecutter-django with docker on windows machine, so far no luck. Now, I want to try to run it on Ubuntu VM, but have hard time to understand how to do that.

Can anyone please put together an instruction for how to install cookiecutter-django with docker on Ubuntu?

**Comment by luzfcb** [comment]
if you are django newbie, this project probably is not the best place to start learn django because he expects you already have a minimum knowledge about how django works, and because the generated project layout is highly opinionated and differs from the project layout generated by `manage.py startproject `
( note that this is not a problem, since Django is just Python with some conventions. there is no magic.) 

I recommend you study and implement all official django tutorial: https://docs.djangoproject.com/en/1.9/intro/

and after implement

http://tutorial.djangogirls.org/

and

http://www.marinamele.com/taskbuster-django-tutorial

About how to install cookiecutter-django with docker on Ubuntu, try this: 

http://cookiecutter-django.readthedocs.org/en/latest/developing-locally-docker.html

**Comment by sakhmedbayev** [comment]
Thank you luzfcb! I appreciate your answer. I have already gone through djangoproject documentation and took some django training. 

The reason why I want to start from cookiecutter is that I found a link to it in "Two Scoops of Django" book, which is considered to be a guide for the best practice in using Django. So, I want to start my Django exploration in the right way :-) Why not?

It seems that my problem is not that much with django as it is with docker or at least with docker on windows or ubuntu.

I just want ask someone who are experienced with cookiecutter to put together a guide for how to install cookiecutter with docker on ubuntu.

**Comment by pydanny** [comment]
Hi @sakhmedbayev, I'm glad you are using my book. And I'm happy you are using cookiecutter-django. Some things you should know:

1. Cookiecutter is not installed with Docker. 
2. Cookiecutter != cookiecutter-django
2. cookiecutter-django provides some Docker setup that is documented in the link @fabio provided. Did you look at that link?
4. If that link doesn't explain it well enough, then on behalf of all the numerous contributors to this project, I apologize.
5. We are unpaid volunteers. As much as we would like to help you out by enhancing that guide, there's only so much time we have to work on the project.

Have you considered figuring out how to do the Docket stuff on your own? And documenting what you did? And then submitting changes to this project. Since you are just getting off the ground work these tools, you will have a view of things that more experienced people lack.

**Comment by sakhmedbayev** [comment]
Thank you @pydanny for your answer and for your awesome book! Sorry for being not precise enough in my writing, I am aware that Cookiecutter != cookiecutter-django.

I have tried to follow several guides for how to install cookiecutter-django with docker. Here they are

[Number one](https://realpython.com/blog/python/development-and-deployment-of-cookiecutter-django-via-docker/)

[Number two](https://realpython.com/blog/python/development-and-deployment-of-cookiecutter-django-on-fedora/)

[Number three (Ubuntu)](http://krzysztofzuraw.github.io/blog/2016/02/19/django-cookiecutter.html)

[Number four](http://cookiecutter-django.readthedocs.org/en/latest/developing-locally-docker.html)

As I wrote, I first tried to install cookiecutter-django with docker on windows machine using Number one guide with a help of [this comment](https://realpython.com/blog/python/development-and-deployment-of-cookiecutter-django-via-docker/#comment-2442262433). This worked in terms of showing homepage of cookiecutter-django, but there are two problems I faced. First, when I tried to run docker container for the second time, let's say on another day, I received an error `mkdir /data: file exists`. I tried to resolve this problem using @mimischi comment in [this issue](https://github.com/pydanny/cookiecutter-django/issues/414). It did not work for me. Second problem was that I had some problem with database, at least, I think it was a problem with database. [Here is what I see if I tried to login as superuser](https://dl.dropboxusercontent.com/u/14947510/error_logs.html)

Then I gave up on windows and tried to install cookiecutter-django on ubuntu using Number Three guide, but following this guide on a step `sudo docker-compose -f dev.yml build`, I received an error `Unsupported config option for services service: 'django'`

I just really want to use cookecutter-django with docker as I see a lot of advantages in this approach, but so far no luck :-(

**Comment by jayfk** [comment]
I know it's frustrating, but instead of following multiple (possible incompatible) tutorials, I'd suggest to debug the problem and become more familiar with docker along the way.

What's the output of

   docker -v
   docker-compose -v
   cat dev.yml (you need to be in your project directory)
   docker run -v ./:/app ls -la /app (you need to be in your project directory)

**Comment by sakhmedbayev** [comment]
Thank you @jayfk ! I finally managed to install cookiecutter-django on ubuntu with docker using Number three guide in my list above. I do not know exactly what caused the problem, but when uninstalled ubuntu 15:10 and installed ubuntu 14:10 everything went pretty smoothly.
