### ISSUE TITLE
App Engine support

### ISSUE THREAD

**Issue by andretietz** [pydanny/cookiecutter-django#560]
Hi everyone,

Will AppEngine be supported on one point? or is that not even planned?

**Comment by pydanny** [comment]
We do not intend to support AppEngine. We will not even accept pull requests for it, because that places the burden of ongoing maintenance on us. As none of the core maintainers of this project use AppEngine, that puts us in the uncomfortable position of providing ongoing free work to benefit a multi-billion dollar multi-national company.

However, if Google is willing to provide staff able to support App Engine here on an ongoing basis, then we are willing to reconsider this decision.
