### ISSUE TITLE
Verify, revise, and improve docs/deployment-with-docker.rst

### ISSUE THREAD

**Issue by audreyr** [pydanny/cookiecutter-django#566]
- Make sure everything is up-to-date.
- If anything is unclear or incorrect, revise the text.

**Comment by jayfk** [comment]
Same here, I'm happy to help if something is unclear.

**Comment by sfdye** [comment]
I don't see any problems with this doc. Maybe it's time to update the minimum docker version though.

**Comment by browniebroke** [comment]
The docs have received a lot of updates since this issue was opened, and I think they are now quite up to date. The minimum version for Docker & compose has been updated as per @sfdye suggestion with #1687, so I'll consider this as done for now. Let's open a new issue if anything specific is wrong there.
