### ISSUE TITLE
Fix flake8 F405 complains?

### ISSUE THREAD

**Issue by valerymelou** [pydanny/cookiecutter-django#631]
Right after project generation, flake8 complains about lot of F405 in local and production settings files. Should we ignore those files with `# flake8: noqua` or just ignore concerned lines with `# noqua`?

**Comment by luzfcb** [comment]
@valerymelou use `# flake8: noqa` does not solve the problem, because it also mutes all other flake8 errors in this file.

This new F405 error was included in flake8 2.6.0.

**Comment by pydanny** [comment]
Should we roll back to an earlier version of flake8? This is annoying seeing all the builds break and not being able to fix it.

**Comment by luzfcb** [comment]
I agree to return to the previous version.

I opened a issue asking for more explanations: https://gitlab.com/pycqa/flake8/issues/146

**Comment by jayfk** [comment]
I'm going to revert #625 to make the build green again. The bot will then open a new (failing) PR where we add commits that fix all other issues.

**Comment by jayfk** [comment]
Reverted in #634, new PR at #635.

**Comment by luzfcb** [comment]
I would not want to mute F405 completely, since `import star` is a bad practice. leaves debug incredibly difficult and confusing. However, our use of `import star` in django configuration file is a case where The Zen of Python: `practicality beats purity` it is applied.

from https://gitlab.com/pycqa/flake8/issues/130#note_12529319, this will be resolved in flake8 3.0.0 .
apparently we will be able to use: `# noqa: F405`

**Comment by valerymelou** [comment]
So we shall fall back to flake8 2.5.5 or wait for flake8 3.0.0 to be able to use `# noqua: F405`.

**Comment by luzfcb** [comment]
@valerymelou the correct is `# noqa: F405` and not `# noqua: F405` :-)

**Comment by valerymelou** [comment]
Thanks @luzfcb , edited.
