### ISSUE TITLE
review the current s3 config

### ISSUE THREAD

**Issue by aleprovencio** [pydanny/cookiecutter-django#632]
The current way leads to problems such as [this](https://stackoverflow.com/questions/12659655/django-storages-sorl-thumbnail-s3-not-working-well-together-urls-mismatch)

**Comment by pydanny** [comment]
Outside of the issue you list, I've never seen any problems with Cookiecutter Django's setup. None of the many other image packages cause any problems to the best of my knowledge. The conclusion I draw is that the issue is with `sorl-thumbnail` and not Cookiecutter Django's configuration. We play according to standard rules, apparently `sorl-thumbnail` does not.

I suggest you open an issue with `sorl-thumbnail`.

**Comment by aleprovencio** [comment]
Thanks @pydanny. I guess this was already [seen](https://github.com/mariocesar/sorl-thumbnail/issues/391) by sorl-thumbnail's crew. Should I insist there then? :)
