### ISSUE TITLE
consider hosts managed though docker-machine

### ISSUE THREAD

**Issue by aleprovencio** [pydanny/cookiecutter-django#658]
This project seems to suggest that docker deploys are based on a workflow where the user logs on the host, pulls code from a git repository and from there runs the docker-compose commands.  I'm using a different approach using docker-machine to just change the active machine to production and do the docker commands.

Using cookiecutter-django on such setup where should I put the supervisor config or the script for certbot renewal? Also as I generate dhparams locally, should put it on the .gitignore?

**Comment by aleprovencio** [comment]
Well I've stopped using docker-machine because it felt silly in a lot of ways so I'm closing this.

**Comment by oesah** [comment]
"stopped using docker-machine because it felt silly", haha, same reason I don't use it to update code etc. I only use it for administration, like starting up a new server instance, checking out my servers, ssh into them via docker-machine etc. But I feel it introduces more complexity into the deployment workflow. So good that I am not the only one, who came to that conclusion :)
