### ISSUE TITLE
Anymail: Domain Not Found Error

### ISSUE THREAD

**Issue by functionallyliterate** [pydanny/cookiecutter-django#666]
Hi,

Just wanted to report a bug with the anymail integration. I attempted to use anymail and mailgun in production the other day and kept receiving a "Domain Not Found Error". According to the anymail docs, it automatically pulls the domain from the sender (From) address domain. So if your sender address is "noreply@xyz.com", it pulls just xyz.com and not the full domain (with mailgun subdomain) needed to send via mailgun.

I got around this by adding adding another Key Value pair to the ANYMAIL config in production.py so that it reads:

```
ANYMAIL = {
    "MAILGUN_API_KEY": env('DJANGO_MAILGUN_API_KEY'),
    "MAILGUN_SEND_DEFAULTS":{
        "esp_extra": {"sender_domain": "mailgun.xyz.com"}
    }
```

I hope this helps someone else if they encounter this issue.

**Comment by aleprovencio** [comment]
That's odd @mbreisch I don't face these problems you mention. Could this be a DNS Records issue?

**Comment by mbreisch** [comment]
@aleprovencio perhaps. But, while following the docs for setting up mailgun I remember it explicitly recommending using a subdomain for the DNS Record required. I followed those recommendations and set it up, with mailgun.mydomain.com. I think anymail expects your DNS Records to have a CNAME for the root domain for mailgun not a subdomain.

**Comment by aleprovencio** [comment]
I've successfully set mailgun with Route 53, setting the suggested values on the domains:

    * txt: mydomain.com and k1._domainkey.mydomain.com
    * cname: email.mydomain.com
    * mx: mydomain.com

Hope this helps!

**Comment by luzfcb** [comment]
@mbreisch @aleprovencio or someone, you have managed to configure mailgun/cookiecuter-django to work without a custom domain ( only using a herokuapp subdomain )

**Comment by aleprovencio** [comment]
@luzfcb , can't tell about that because I don't heroku, but as you see my settings above I don't use a mailgun subdomain on DNS Records.

**Comment by mbreisch** [comment]
@aleprovencio I think I misspoke before regarding the CNAME record, I meant TXT record--it was a long day, I edited that post. I did not set the CNAME or mxrecords as they are optional, I did not need  email tracking or receiving through mailgun. My DNS is Cloudflare and my records for mailgun are:
`txt: mailgun.mydomain.com and k1._domainkey.mailgun.mydomain.com`.

Thanks for posting your DNS records, I think that pretty much confirms my theory, since the only difference seems to be my use of a subdomain rather than using the root domain for my mailgun txt.

@luzfcb I have not tried this on Heroku itself, but, I've gotten anymail with mailgun to work with a similar PAAS, Flynn, and did not have any issues. I set up mailgun with a domain name I owned that I planned to provide a cname to the Flynn generated subdomain. So I setup the mailgun txt records with mydomain.com and then pointed a cname of mydomain.com to the Flynn url mydomain.flynnhub1.com. Did you setup your environment variables? Are you able to curl to the mailgun api using the credentials you setup with mailgun?

**Comment by browniebroke** [comment]
The settings looked like this when this issue was opened:
https://github.com/pydanny/cookiecutter-django/blob/a658339b99a76c8270a9fe418eb3d3edc12a27b2/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/production.py#L161-L166

Shortly after the last comment, another setting was added to set the domain more easily in https://github.com/pydanny/cookiecutter-django/commit/3d25befb3f43d8965816376a4e64b868e0db6f6d:

https://github.com/pydanny/cookiecutter-django/blob/60ebda8bf7b0cc0c752ff813a125316d3cb79ad3/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/production.py#L142-L147

Assume this is fixed now, we can re-open if needed.
