### ISSUE TITLE
Cookecutter with Visual Studio

### ISSUE THREAD

**Issue by arcanewater** [pydanny/cookiecutter-django#733]
Has anyone tryed it to get it properly working with VS and Python tools? Are there any plans to make a option like there is for pycharm?

**Comment by luzfcb** [comment]
@arcanewater 
all maintainers use mainly OSX and Linux as development machine, (and from my personal experience, support any non-Microsoft tool in windows, can be an incredible headache.)
then there is no any plans to include support to another editor, because we do not have time or energy to provide non-paid support to another editor.

(unless MS or other want to pay someone to maintain the support)

**Comment by pydanny** [comment]
I don't see it happening but it would be grand if @microsoft became a sponsor for this project. 😀
