### ISSUE TITLE
django-compressor doesn't always work on Windows

### ISSUE THREAD

**Issue by pydanny** [pydanny/cookiecutter-django#737]
It uses [rcssmin](https://github.com/ndparker/rcssmin) which uses C extensions in order to optimize minification. This can break for Windows users.

Options:

* Leave django-compressor in, but filter out windows users (makes me not happy)
* Find a non-C extension version of django-compressor (not likely)
* Make it possible to use django-compressor without a C compiler
* Get the maintainers to upload a wheel, which **might resolve the problem**

**Comment by jayfk** [comment]
We should find a solution here as the current build is broken on docker and linux, see #748, #743.

Suggestion:

* Make `--install-option="--without-c-extensions" ` for windows users only (for now).
* Check options 2+3 and go on from there.

**Comment by pydanny** [comment]
I made `--install-option="--without-c-extensions"` be for Windows users only.

**Comment by luzfcb** [comment]
@jayfk 

> Make --install-option="--without-c-extensions" for windows users only (for now).

This solve the problems to linux/mac users, but not completely solve to windows users.

I think `--install-option="--without-c-extensions"` will also break on windows, because the problem is `pip`. 

Apparently `--install-option =" - without-c-extensions "` is applied to all next packages to be installed and not only ` rcssmin`.
