### ISSUE TITLE
Install on Ubuntu 14.04 via requirements/base.txt breaking on django-compressor==2.1

### ISSUE THREAD

**Issue by seanbradley** [pydanny/cookiecutter-django#748]
Commenting out the requirement enables install to complete successfully.

```
Command "/home/<username>/.virtualenvs/boilerplate/bin/python3 -u -c "import setuptools, 
tokenize;__file__='/tmp/user/1001/pip-build-59ihng3m/django-
appconf/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), 
__file__, 'exec'))" install --record /tmp/user/1001/pip-3hlmfx2j-record/install-record.txt --single-
version-externally-managed --compile --install-headers 
/home/<username>/.virtualenvs/<projectname>/include/site/python3.4/django-appconf --without-c-
extensions" failed with error code 1 in /tmp/user/1001/pip-build-59ihng3m/django-appconf/
```

**Comment by luzfcb** [comment]
I believe this can be a bug in `pip` (or expected behavior `¯\_(ツ)_/¯`)

include `--install-option="anything_option_here"` does break the package installation of the first uninstalled package, immediately after the statement.


bug introduced on cookiecutter-django in https://github.com/pydanny/cookiecutter-django/commit/87bb085550df6813d9f90b0a2e1ee6c56b1e800d

related issue #743: 


to reproduce issue:

create a requirement file `req_test.txt` and put:

```
rcssmin==1.0.6 --install-option="--without-c-extensions"
django-compressor==2.1 #is installed
requests # is uninstalled and break install
```
and run

```
pip install -r req_test.txt --no-cache-dir -U
```

it also breaks

```
pip uninstall -r req_test.txt
```

**Comment by pydanny** [comment]
I think this is resolved in d98bbcd70e926016bc526a2083d158440ac29de5. Please confirm.

**Comment by seanbradley** [comment]
I was able to solve the problem with installing django-compressor==2.1 on Ubuntu 14.04 (Trusty) after upgrading my python3 header files and a static library via...

sudo apt-get install python3-dev

This may have also been the cause of earlier problems related to installing psycopg2 in cookiecutter-django requirements.

**Comment by spoetnik** [comment]
Confirmed this issue is fixed. Thanks!!
