### ISSUE TITLE
heroku deploy user login/create gives 500

### ISSUE THREAD

**Issue by sglyon** [pydanny/cookiecutter-django#789]
If I run the cookie cutter, follow the steps on the deploy to heroic doc page, then actually do the deployment I get a 500 error everything time I try to log in as the super user I created when following docs.

Is there something I'm missing -- perhaps additional steps that should be added to the doc page?

**Comment by ssteinerx** [comment]
In my opinion, heroku support should be moved out of the main project into a "plugin/mixin" for the very reason that this project should not be directly supporting specific deployment options but should only include a Django "best practices" template which should have "plugin/mixin"s that support the various options.

That said, what are in the various logs on Heroku?

**Comment by spencerlyon2** [comment]
I think this one is user error. When I enable debug and deploy to heroku again I see that the problem is with my email config.

Any tips on how to configure the email settings [here](https://github.com/pydanny/cookiecutter-django/blob/9f2fa4a0a91a55f2c565661556e2f55a47ad400d/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/production.py#L157-L158)?

**Comment by ssteinerx** [comment]
Is cookiecutter.domain_name set properly?

**Comment by spencerlyon2** [comment]
It probably isn't. 

I think what I need to do is configure the heroku mailgun add on, but I'm not sure how to do that... I'm pretty new to building web apps, so I'm probably just missing something obvious. I'll try to keep looking.

**Comment by jangeador** [comment]
Because of a setting in anymail you have to make sure that the email on your config domain name matches the subdomain at mailgun. So if you used `mg.yourdomain.com` as the mailgun subdomain, then your email in the config should be something like `admin_email@mg.yourdomain.com`. They have fixed this in anymail already, however, they have not made a release since they fixed this.

**Comment by pydanny** [comment]
@jangeador Did you get this working?

**Comment by moizjv** [comment]
I think you might be missing migrate step
