### ISSUE TITLE
Missing template account/snippets/already_logged_in.html

### ISSUE THREAD

**Issue by yunti** [pydanny/cookiecutter-django#791]
From the password reset form the already logged in template looks to be missing.  Was this just omitted in error from django allauth or is there another reason?

**Comment by pydanny** [comment]
It's not included because there's no reason for us to override what django-allauth provides via https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/snippets/already_logged_in.html. Bootstrap won't break on paragraph or strong tags. 

If an error is being thrown, or formatting is off, please reopen.

**Comment by yunti** [comment]
Good point! Thanks..
