### ISSUE TITLE
Integrate/running this project on vagrant with docker

### ISSUE THREAD

**Issue by ibnbay99** [pydanny/cookiecutter-django#907]
How to integrate/running this project on vagrant with docker?
Anyone can explain how?
Thanks....

**Comment by ibnbay99** [comment]
For development, i think because with vagrant is easy to deliver to difference os (my team using windows and linux :))
It is not good practice?
Please enlightenment me, because i'm newbie on vagrant and docker.

Thanks

**Comment by mimischi** [comment]
@ibnbay99 You're supposed to be able to use Docker on all OS during development. This project works with OS X, Linux and Windows.

Are you having any problems?

**Comment by ssteinerx** [comment]
@pydanny I can't speak to Windows (thankfully) but there are definitely differences between using Docker native on  Linux and OS X.  OS X maps directories differently e.g.:

```bash
lrwxr-xr-x@ 1 root  wheel    11B May 19  2016 /etc -> private/etc
```

so setting up on an OS X box often doesn't map 1:1 with a Linux deployment.

I use the built-in Docker (on OS X) for some things, but find Vagrant + Docker (or VirtualBox + Docker) easier to keep straight in my head at deployment time.

**Comment by pydanny** [comment]
@ssteinerx While the differences in Docker usage with different operating systems are an issue, I don't think they are that significant. And those differences could be accounted for in documentation, rather than re-adding Vagrant to the project.

@ibnbay99, This project used to have Vagrant as one of the components. By adding Docker that gave us the liberty to remove it. Why did we remove it? In short, it was a maintenance burden that took us away from other areas of the project that we were more excited about (Docker, PyCharm, et al).

I'm closing this as a wontfix. If someone wants to hire one of the core developers on an ongoing basis to add and maintain Vagrant back into the project, we'll reopen it.

**Comment by ssteinerx** [comment]
@pydanny I wasn't advocating for putting it back in -- too much of a pain to maintain and the differences don't go *that* far away between operating systems.
