### ISSUE TITLE
Add uWsgi as an alternative option to Gunicorn

### ISSUE THREAD

**Issue by schacki** [pydanny/cookiecutter-django#926]
Currently, it is only possible, to deliver the production Django project via gunicorn. I would like to add one option, that let the user choose between uWsgi and Gunicorn.
I ok, I am happy to provide a PR.

**Comment by jayfk** [comment]
I'm a huge `uWsgi` fan and would love to have this as an option in Cookiecutter Django. We have, however, a lot of platforms people using this project deploy to.

If we add `uWsgi` as an option we have to make sure it works on all platforms and continues to do so in the long run. Considering the time and effort to do this, it is unlikely that one of the maintainers is willing to do that at the moment.

**Comment by schacki** [comment]
Hm, maybe I underestimate the complexity. But in general, there are various (deployment) options, that do exclude each other. E.g. docker will not run on Heroku, or Procfile is not required for a lot of platforms. 

Adding a uWsgi option, for those people who like to use it on their platform or within Docker should do no harm. Anybody could still opt for gunicorn.

And the code changes should not be to big.

**Comment by pydanny** [comment]
Docker, which I presume is your target, works the same everywhere, right? Erm... not quite. Docker's behavior can have subtle differences on Windows, Linux, and Mac OSX. Which beggars the following questions:

1. Will the uWSGI modifications you submit be tested on Windows 10, Linux, and Mac OSX?
2. What assurances can you give that you will be able to support and help people with problems for 5-10 hours a week here and on Gitter for as long as Cookiecutter Django supports your uWSGI modifications? Is your place of employment willing to pay for your maintenance work on this project?

Submissions for new features in Cookiecutter Django are something we enjoy. However, we have to balance to additional maintenance work we (the maintainers) have to do in order to have that new feature.

**Comment by schacki** [comment]
Well, obviously I did underestimate the complexity, and requirements in terms of testing and platform support. Thanks for the detailed explaination.

**Comment by theskumar** [comment]
@schacki django-init switched to uWSGI recently, our setup is based/tested only for ubuntu16 for production deployment using ansible ( https://github.com/Fueled/django-init/pull/191 ). You can try out if it helps you in anyways. 

Having a less stacks to maintain it allows us to move fast. That's not the case with this project. I do see a substantial effort involved for the change. 

My 2 cents.

**Comment by schacki** [comment]
In my fork at https://github.com/webspired/cookiecutter-django, I have added the option to serve the project via uWsgi and the static files via uWsgi static file handler.
I made sure that Gunicorn is still the default and added warnings to use uWsgi outside of Docker only at your own risk.

I will keep that branch open for anybody that is interested to use it.

Feedback welcome.
