### ISSUE TITLE
Forbidden (403) CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by piyushmaurya23** [pydanny/cookiecutter-django#958]
I am using `http` instead of `https`. Please tell me which setting I need to change to workout with this error.

1. I think this problem is because I am using `http` instead of `https`.
2. Works on heroku, works on development, this error is only happening when I deployed it using docker in production.

**Comment by pydanny** [comment]
Sounds like you need to set up Let's Encrypt. That's one of the docker-related options we provide.

**Comment by Chris7** [comment]
I hit this problem as well but have an additional problem that I'm setting up an internal site so Let's Encrypt cannot reach my site. I ended up just dropping cookiecutter bootstrap for a simple Django project setup, but I wanted to point out that some sites cannot use Let's Encrypt and might want to use cookiecutter-django to get a decent bootstrap setup.

**Comment by Afrowave** [comment]
I have stumbled into this for two projects. For the first, I had to rebase to a django 1.9.9 commit and rebuild from there when I discovered all my upgrade work in development did not count.

On the second project, I am to use *Lets Encrypt* but the client has not committed to the URL so I disabled it in the ```docker-compose.yml``` while building to the staging server.  But I can not get to the admin to make sure all is well.

I spun up a vanilla Cookiecut Django project, tested in development, no problem. But on going onto a Digital Ocean droplet for staging, I get the *'Forbidden (403) CSRF verification failed. Request aborted.'* after logging into the Admin.

Am I to believe that we have no way of going round this apart from installing Lets Encrypt? Is it a @pydanny and team decision?

I commit to do the documentation on the agreement made on this issue. It's a show stopper.

**Comment by pydanny** [comment]
It's not stated, but Cookiecutter Django is secure by default. We believe in SSL by default. The last thing we want is for this project to be connected to a security failure.

We do provide the option to not use Let's Encrypt, but then the onus is on users to implement on their own HTTPS to allow for easy CSRF.

This is not going to change. We are not going to diminish security.

If this is a serious obstacle for you, I suggest the following:

1. Fork this project and remove the Let's Encrypt sections.
2. Hire one of the Cookiecutter Django devs to help you around the SSL issues you face.

**Comment by Afrowave** [comment]
*"Hire one of the Cookiecutter Django devs to help you around the SSL issues you face."*
I saw what you did over there.

@pydanny Oh don't get me wrong. I love Cookiecutter Django and that it is secure by default. My consternation is that it crept up on me and bit my b$#t.

I think it should be stated, *(explicit is better than implicit)*. It would be especially kind to noobs who need to understand from the get-go that this project is the "meat and potatoes" *(english - meaning "the real deal")*. :-D

 I will write up something and submit a PR and we see where to go from there.

**Comment by polinom** [comment]
For those that do want to go **insecure** without installing ssl. 

Set in your settings:

```
      CSRF_COOKIE_HTTPONLY = False
      CSRF_COOKIE_SECURE = False
```

**Comment by pydanny** [comment]
@polinom, I deleted your post because I categorically refuse to have any project I'm leading to be in any way affiliated with a security failure. If you want to describe how to make django **less secure**, do it in your own project.

Please don't do something like this again. I feel very strongly about this, and if necessary, I will block you from all my projects.

**Comment by jayfk** [comment]
I wonder if it would make sense to use caddy instead of nginx on docker to make this even easier.

We're using Caddy on djangopackages.com and it's doing well so far.

**Comment by Afrowave** [comment]
For those who have purchased the *Django - Two Scoops*, @pydanny does take security seriously and has a whole chapter dedicated to it.

Personally, I had not taken it seriously since I use Django (pretty solid), SSL was a certificate cost until recently that my clients didn't want unless it was critical. So I had grown accustomed to the security alert *noise* sent to me by **sentry.io** of people trying to hack into my servers. But is only recently that I was wondering if a server I set up was running because I received no warning from it. It is on HTTPS and thanks to this project, it was effortless.

The hits are very low for small companies in Kenya, East Africa. But if 5 - 10% are *"Invalid HTTP_HOST header"* errors that go to nothing on HTTPS, then I will stick with HTTPS. **Lets Encrypt** has removed the cost of the certificate. But a valid domain name is required to register HTTPS.

**Comment by yshterev** [comment]
@pydanny I get the same error. Will it work if I use the free SSL from CloudFlare ?

**Comment by Afrowave** [comment]
@yshterev It should. I am assuming you mean this - [Adding HTTPS For Free With Cloudflare](https://pantheon.io/docs/guides/cloudflare-enable-https/).

It should work without any other problems.

**Comment by yshterev** [comment]
Yes. It works fine. Thanks for the quick response.
